import type { JobData, ResumeData, CoverLetterData, JobState } from "./types"

export const defaultJobStates: JobState[] = [
  { id: "wishlist", name: "Wishlist", color: "#4A90E2", order: 0, isDefault: true, isSystem: true }, // Blue
  { id: "applied", name: "Applied", color: "#F5A623", order: 1, isSystem: true },  // Orange
  { id: "interview", name: "Interview", color: "#7ED321", order: 2, isSystem: true }, // Green
  { id: "offer", name: "Offer", color: "#BD10E0", order: 3, isSystem: true },      // Purple
  { id: "rejected", name: "Rejected", color: "#D0021B", order: 4, isSystem: true }  // Red
];

export const initialJobs: JobData[] = [
  {
    id: "1",
    company: "Vercel",
    position: "Frontend Developer",
    location: "San Francisco, USA",
    workMode: "remote",
    salaryMin: 120000,
    salaryMax: 150000,
    salaryCurrency: "USD",
    date: "2023-08-15",
    applyDate: "2023-08-15",
    status: "applied",
    notes: "Applied through company website",
    url: "https://vercel.com/careers",
    priority: 5,
    skills: ["React", "Next.js", "TypeScript"],
    softSkills: [],
    requirements: [],
    description: "Looking for an experienced frontend developer with strong React and Next.js skills.",
  },
  {
    id: "2",
    company: "Stripe",
    position: "Full Stack Engineer",
    location: "San Francisco, USA",
    workMode: "hybrid",
    salaryMin: 130000,
    salaryMax: 160000,
    salaryCurrency: "USD",
    date: "2023-08-10",
    applyDate: "2023-08-10",
    status: "interview",
    notes: "First interview scheduled for next week",
    url: "https://stripe.com/jobs",
    priority: 4,
    skills: ["React", "Node.js", "PostgreSQL"],
    softSkills: [],
    requirements: [],
    description: "Building payment infrastructure for the internet.",
  },
  {
    id: "3",
    company: "Airbnb",
    position: "Senior Frontend Engineer",
    location: "Berlin, Germany",
    workMode: "remote",
    salaryMin: 140000,
    salaryMax: 170000,
    salaryCurrency: "USD",
    date: "2023-08-05",
    status: "wishlist",
    url: "https://airbnb.com/careers",
    priority: 3,
    skills: ["React", "JavaScript", "CSS"],
    softSkills: [],
    requirements: [],
    description: "Join our team to build the future of travel and accommodations.",
  },
  {
    id: "4",
    company: "Netflix",
    position: "UI Engineer",
    location: "Los Gatos, CA",
    salary: "$150k - $180k",
    date: "2023-07-28",
    status: "rejected",
    notes: "Rejected after technical interview",
    url: "https://netflix.com/jobs",
    priority: 2,
    skills: ["React", "JavaScript", "A/B Testing"],
    softSkills: [],
    requirements: [],
    description: "Creating engaging user interfaces for our streaming platform.",
  },
  {
    id: "5",
    company: "Shopify",
    position: "Frontend Developer",
    location: "Remote",
    salary: "$110k - $140k",
    date: "2023-08-12",
    status: "offer",
    notes: "Received offer, need to respond by next week",
    url: "https://shopify.com/careers",
    priority: 5,
    skills: ["React", "Ruby on Rails", "GraphQL"],
    softSkills: [],
    requirements: [],
    description: "Building tools to help entrepreneurs start and grow their businesses.",
  },
  {
    id: "6",
    company: "Microsoft",
    position: "Software Engineer",
    location: "Redmond, WA",
    salary: "$130k - $160k",
    date: "2023-08-01",
    status: "applied",
    notes: "Applied through referral",
    url: "https://microsoft.com/careers",
    priority: 4,
    skills: ["C#", ".NET", "Azure"],
    softSkills: [],
    requirements: [],
    description: "Developing cloud solutions for enterprise customers.",
  },
  {
    id: "7",
    company: "Google",
    position: "Frontend Engineer",
    location: "Mountain View, CA",
    salary: "$140k - $180k",
    date: "2023-07-25",
    status: "wishlist",
    url: "https://careers.google.com",
    priority: 5,
    skills: ["JavaScript", "Angular", "Web Performance"],
    softSkills: [],
    requirements: [],
    description: "Building fast, responsive web applications used by millions of people.",
  },
  {
    id: "8",
    company: "Amazon",
    position: "UI/UX Developer",
    location: "Seattle, WA",
    salary: "$125k - $155k",
    date: "2023-08-08",
    status: "interview",
    notes: "Second round interview scheduled",
    url: "https://amazon.jobs",
    priority: 4,
    skills: ["React", "AWS", "User Experience"],
    softSkills: [],
    requirements: [],
    description: "Creating intuitive shopping experiences for customers worldwide.",
  },
]

export const initialResumes: ResumeData[] = [
  {
    id: "1",
    title: "Software Developer Resume",
    originalName: "software_dev_resume.pdf",
    lastUpdated: "2023-08-01",
    format: "PDF",
    size: "245 KB",
    content:
      "Frontend developer with 5+ years of experience building responsive web applications with React, TypeScript, and modern CSS frameworks. Proficient in Next.js, Node.js, and GraphQL. Strong problem-solving skills and experience working in agile teams.",
  },
  {
    id: "2",
    title: "Frontend Developer Resume",
    originalName: "frontend_dev_resume.pdf",
    lastUpdated: "2023-07-15",
    format: "PDF",
    size: "198 KB",
    content:
      "Experienced frontend developer specializing in React, JavaScript, and CSS. Created responsive web applications with modern frameworks like Next.js and Tailwind CSS. Skilled in performance optimization and accessibility.",
  },
]

export const initialCoverLetters: CoverLetterData[] = [
  {
    id: "1",
    title: "Frontend Developer",
    company: "Tech Startups",
    lastUpdated: "2023-08-05",
    content:
      "Dear Hiring Manager,\n\nI am writing to express my interest in the Frontend Developer position at your company. With over 5 years of experience building responsive and accessible web applications using React, TypeScript, and modern CSS frameworks, I believe I would be a valuable addition to your team.\n\nThroughout my career, I have focused on creating exceptional user experiences while maintaining clean, efficient code. I am particularly proud of my work at...[truncated]",
  },
  {
    id: "2",
    title: "Full Stack Developer",
    company: "Enterprise Companies",
    lastUpdated: "2023-07-20",
    content:
      "Dear Hiring Team,\n\nI am writing to apply for the Full Stack Developer position at your organization. With a strong background in both frontend and backend technologies, including React, Node.js, and SQL/NoSQL databases, I am confident in my ability to contribute to your development team from day one.\n\nIn my current role at XYZ Corp, I've successfully led the development of several mission-critical applications that have improved operational efficiency by 35%. I've collaborated closely with cross-functional teams to deliver scalable solutions that meet both business requirements and technical standards.\n\nI am particularly interested in your company because of your commitment to innovation and your impressive product portfolio. I believe my technical expertise and problem-solving skills would be valuable assets to your team.",
  },
]
