/**
 * Curated lists of skills and requirements for job analysis
 */

// Technical skills organized by category
export const technicalSkillsMap: Record<string, string[]> = {
  "Programming Languages": [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "C",
    "PHP",
    "Ruby",
    "Go",
    "Golang",
    "Swift",
    "Kotlin",
    "Rust",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Shell",
    "Bash",
    "PowerShell",
    "Groovy",
    "Objective-C",
    "Dart",
    "Lua",
    "Haskell",
    "Clojure",
    "Elixir",
    "F#",
    "COBOL",
    "Fortran",
    "Assembly",
    "VBA",
    "VB.NET",
    "Delphi",
    "Julia",
    "Apex",
    "SAS",
    "ABAP",
    "PL/SQL",
    "T-SQL",
  ],
  "Web Technologies": [
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "SASS",
    "SCSS",
    "Less",
    "Bootstrap",
    "Tailwind",
    "Material UI",
    "Chakra UI",
    "Styled Components",
    "Emotion",
    "React",
    "Angular",
    "Vue",
    "Svelte",
    "jQuery",
    "Redux",
    "MobX",
    "Zustand",
    "Next.js",
    "Gatsby",
    "Nuxt",
    "Astro",
    "Remix",
    "Express",
    "Node.js",
    "Deno",
    "Bun",
    "Electron",
    "PWA",
    "Web Components",
    "Shadow DOM",
    "WebSockets",
    "WebRTC",
    "WebGL",
    "Canvas API",
    "SVG",
    "D3.js",
    "Three.js",
    "WebAssembly",
    "WASM",
    "Service Workers",
    "Web Workers",
    "IndexedDB",
    "LocalStorage",
    "SessionStorage",
    "REST API",
    "GraphQL",
    "Apollo",
    "Relay",
    "JSON",
    "XML",
    "AJAX",
    "Fetch API",
    "Axios",
    "JWT",
    "OAuth",
    "SSO",
    "CORS",
    "CSP",
    "SPA",
    "SSR",
    "SSG",
    "ISR",
    "Responsive Design",
    "Mobile First",
    "Progressive Enhancement",
  ],
  "Frameworks & Libraries": [
    "Laravel",
    "Django",
    "Flask",
    "FastAPI",
    "Spring",
    "Spring Boot",
    "ASP.NET",
    "ASP.NET Core",
    "Rails",
    "Ruby on Rails",
    "Symfony",
    "CodeIgniter",
    "Struts",
    "Hibernate",
    "Entity Framework",
    "NestJS",
    "Express.js",
    "Koa.js",
    "Hapi.js",
    "Meteor",
    "Sails.js",
    "Phoenix",
    "Play Framework",
    "Gin",
    "Echo",
    "Fiber",
    "Rocket",
    "Actix",
    "Axum",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Hugging Face",
    "Transformers",
    "NLTK",
    "spaCy",
    "Gensim",
    "OpenCV",
    "Pillow",
    "Beautiful Soup",
    "Scrapy",
    "Selenium",
    "Puppeteer",
    "Playwright",
    "Jest",
    "Mocha",
    "Chai",
    "Jasmine",
    "Cypress",
    "Enzyme",
    "React Testing Library",
    "JUnit",
    "TestNG",
    "pytest",
    "unittest",
    "PHPUnit",
    "RSpec",
    "Mockito",
    "Sinon",
    "Vitest",
  ],
  Databases: [
    "SQL",
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "SQL Server",
    "SQLite",
    "MongoDB",
    "Cassandra",
    "Redis",
    "DynamoDB",
    "Elasticsearch",
    "Neo4j",
    "MariaDB",
    "Firebase",
    "Firestore",
    "Supabase",
    "CouchDB",
    "GraphQL",
    "Fauna",
    "Couchbase",
    "RethinkDB",
    "InfluxDB",
    "TimescaleDB",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Teradata",
    "Vertica",
    "Clickhouse",
    "Pinecone",
    "Milvus",
    "Qdrant",
    "Weaviate",
    "Chroma",
    "PlanetScale",
    "Cockroach DB",
    "Dgraph",
    "ArangoDB",
    "RavenDB",
    "HBase",
    "Bigtable",
    "Cosmos DB",
    "Realm",
    "Prisma",
    "Sequelize",
    "TypeORM",
    "Mongoose",
    "SQLAlchemy",
    "Hibernate",
    "JDBC",
    "ADO.NET",
    "Dapper",
    "Entity Framework Core",
  ],
  "Cloud & DevOps": [
    "AWS",
    "Amazon Web Services",
    "EC2",
    "S3",
    "Lambda",
    "ECS",
    "EKS",
    "RDS",
    "DynamoDB",
    "CloudFront",
    "Route53",
    "IAM",
    "Azure",
    "Microsoft Azure",
    "Azure Functions",
    "Azure DevOps",
    "Azure Kubernetes Service",
    "Azure SQL",
    "Azure Cosmos DB",
    "Azure Storage",
    "GCP",
    "Google Cloud",
    "Google Cloud Platform",
    "Google Compute Engine",
    "Google Kubernetes Engine",
    "Cloud Storage",
    "BigQuery",
    "Cloud Functions",
    "Cloud Run",
    "Heroku",
    "Netlify",
    "Vercel",
    "Digital Ocean",
    "Linode",
    "Vultr",
    "OVH",
    "Scaleway",
    "Render",
    "Fly.io",
    "Railway",
    "Docker",
    "Docker Compose",
    "Docker Swarm",
    "Kubernetes",
    "K8s",
    "Helm",
    "Istio",
    "Linkerd",
    "Service Mesh",
    "CI/CD",
    "Continuous Integration",
    "Continuous Deployment",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "GitHub Actions",
    "GitLab CI",
    "Bitbucket Pipelines",
    "ArgoCD",
    "Flux CD",
    "Terraform",
    "Pulumi",
    "CloudFormation",
    "ARM Templates",
    "Bicep",
    "Infrastructure as Code",
    "IaC",
    "Ansible",
    "Puppet",
    "Chef",
    "Salt",
    "Prometheus",
    "Grafana",
    "Datadog",
    "New Relic",
    "Dynatrace",
    "AppDynamics",
    "Splunk",
    "ELK Stack",
    "Elasticsearch",
    "Logstash",
    "Kibana",
    "Fluentd",
    "Jaeger",
    "Zipkin",
    "OpenTelemetry",
    "Sentry",
    "PagerDuty",
    "OpsGenie",
    "VictorOps",
    "Site Reliability Engineering",
    "SRE",
    "DevSecOps",
    "GitOps",
    "Chaos Engineering",
  ],
  "Tools & Version Control": [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Subversion",
    "Mercurial",
    "Perforce",
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Monday",
    "ClickUp",
    "Notion",
    "Linear",
    "Shortcut",
    "Basecamp",
    "Airtable",
    "Figma",
    "Sketch",
    "Adobe XD",
    "InVision",
    "Zeplin",
    "Photoshop",
    "Illustrator",
    "After Effects",
    "Premiere Pro",
    "Blender",
    "Unity",
    "Unreal Engine",
    "Visual Studio",
    "Visual Studio Code",
    "VS Code",
    "IntelliJ IDEA",
    "WebStorm",
    "PyCharm",
    "PhpStorm",
    "Rider",
    "CLion",
    "GoLand",
    "Android Studio",
    "Xcode",
    "Eclipse",
    "NetBeans",
    "Atom",
    "Sublime Text",
    "Vim",
    "Emacs",
    "Jupyter Notebook",
    "Jupyter Lab",
    "Google Colab",
    "Postman",
    "Insomnia",
    "cURL",
    "Swagger",
    "OpenAPI",
    "Slack",
    "Microsoft Teams",
    "Discord",
    "Zoom",
    "Google Meet",
    "Miro",
    "Lucidchart",
    "Draw.io",
    "Excalidraw",
  ],
  "Microsoft Technologies": [
    ".NET",
    ".NET Core",
    ".NET Framework",
    ".NET MAUI",
    "ASP.NET",
    "ASP.NET Core",
    "ASP.NET MVC",
    "ASP.NET Web API",
    "ASP.NET Web Forms",
    "ASP.NET Razor Pages",
    "ASP.NET SignalR",
    "Blazor",
    "Blazor Server",
    "Blazor WebAssembly",
    "Razor",
    "Razor Components",
    "C#",
    "C# 10",
    "C# 11",
    "C# 12",
    "VB.NET",
    "Visual Basic .NET",
    "F#",
    "Entity Framework",
    "Entity Framework Core",
    "EF Core",
    "Dapper",
    "ADO.NET",
    "WPF",
    "Windows Presentation Foundation",
    "UWP",
    "Universal Windows Platform",
    "WinUI",
    "WinForms",
    "Windows Forms",
    "WCF",
    "Windows Communication Foundation",
    "LINQ",
    "Language Integrated Query",
    "NuGet",
    "MSBuild",
    "Roslyn",
    ".NET Standard",
    "Xamarin",
    "Xamarin.Forms",
    "Xamarin.Android",
    "Xamarin.iOS",
    "Mono",
    "Unity",
    "ML.NET",
    "SharePoint",
    "SharePoint Online",
    "Dynamics 365",
    "Dynamics CRM",
    "Power BI",
    "Power Apps",
    "Power Automate",
    "Power Platform",
    "Power Virtual Agents",
    "Office 365",
    "Microsoft 365",
    "Exchange",
    "Exchange Online",
    "OneDrive",
    "Teams",
    "Microsoft Teams",
    "Outlook",
    "Word",
    "Excel",
    "PowerPoint",
    "Access",
    "VBA",
    "Visual Basic for Applications",
    "Azure DevOps",
    "VSTS",
    "Visual Studio Team Services",
    "TFS",
    "Team Foundation Server",
    "Visual Studio",
    "Visual Studio Code",
    "SQL Server",
    "SSRS",
    "SQL Server Reporting Services",
    "SSIS",
    "SQL Server Integration Services",
    "SSAS",
    "SQL Server Analysis Services",
    "T-SQL",
    "Transact-SQL",
    "Windows Server",
    "Active Directory",
    "Azure Active Directory",
    "Azure AD",
    "Entra ID",
    "Hyper-V",
    "PowerShell",
    "Windows Terminal",
    "WSL",
    "Windows Subsystem for Linux",
  ],
  Mobile: [
    "Android",
    "Android Development",
    "Android SDK",
    "Android Studio",
    "Jetpack Compose",
    "iOS",
    "iOS Development",
    "Swift",
    "SwiftUI",
    "UIKit",
    "Objective-C",
    "Xcode",
    "React Native",
    "Flutter",
    "Dart",
    "Xamarin",
    "Xamarin.Forms",
    "Ionic",
    "Cordova",
    "PhoneGap",
    "Capacitor",
    "NativeScript",
    "Kotlin",
    "Kotlin Multiplatform",
    "KMM",
    "Java for Android",
    "Mobile UI Design",
    "Responsive Design",
    "Progressive Web Apps",
    "PWA",
    "Mobile Testing",
    "Firebase",
    "Push Notifications",
    "In-App Purchases",
    "App Store Optimization",
    "ASO",
    "Google Play Store",
    "Apple App Store",
    "Mobile Analytics",
    "Mobile Security",
    "Offline Storage",
    "Mobile Performance",
    "Mobile Accessibility",
    "Mobile Gestures",
    "Mobile Navigation",
    "Deep Linking",
    "App Clips",
    "Instant Apps",
    "ARKit",
    "ARCore",
    "Augmented Reality",
    "Virtual Reality",
    "Mobile VR",
    "Mobile AR",
    "Mobile Payments",
    "Mobile Authentication",
    "Biometrics",
    "Face ID",
    "Touch ID",
    "Mobile Maps",
    "Location Services",
    "Geolocation",
    "Bluetooth",
    "BLE",
    "Bluetooth Low Energy",
    "NFC",
    "Near Field Communication",
  ],
  Testing: [
    "Jest",
    "Mocha",
    "Chai",
    "Jasmine",
    "Cypress",
    "Selenium",
    "Puppeteer",
    "Playwright",
    "WebdriverIO",
    "Protractor",
    "JUnit",
    "NUnit",
    "xUnit",
    "TestNG",
    "PHPUnit",
    "RSpec",
    "Pytest",
    "unittest",
    "Vitest",
    "Testing Library",
    "React Testing Library",
    "Vue Testing Library",
    "Angular Testing Library",
    "Enzyme",
    "Sinon",
    "Mock",
    "Stub",
    "Spy",
    "Faker",
    "MSTest",
    "Mockito",
    "EasyMock",
    "PowerMock",
    "JMock",
    "TDD",
    "Test-Driven Development",
    "BDD",
    "Behavior-Driven Development",
    "ATDD",
    "Acceptance Test-Driven Development",
    "Unit Testing",
    "Integration Testing",
    "E2E Testing",
    "End-to-End Testing",
    "Functional Testing",
    "Regression Testing",
    "Smoke Testing",
    "Sanity Testing",
    "Performance Testing",
    "Load Testing",
    "Stress Testing",
    "Security Testing",
    "Penetration Testing",
    "Pen Testing",
    "Vulnerability Assessment",
    "Accessibility Testing",
    "A11y Testing",
    "WCAG",
    "Web Content Accessibility Guidelines",
    "Manual Testing",
    "Automated Testing",
    "Test Automation",
    "Test Cases",
    "Test Plans",
    "Test Strategy",
    "Test Management",
    "TestRail",
    "Zephyr",
    "qTest",
    "Quality Assurance",
    "QA",
    "Quality Control",
    "QC",
    "Continuous Testing",
    "API Testing",
    "Postman",
    "SoapUI",
    "JMeter",
    "Gatling",
    "Locust",
    "K6",
    "Artillery",
    "Code Coverage",
    "Istanbul",
    "Codecov",
    "Coveralls",
    "SonarQube",
    "ESLint",
    "TSLint",
    "Prettier",
    "Stylelint",
    "Lighthouse",
    "WebPageTest",
    "Cucumber",
    "Gherkin",
    "SpecFlow",
    "Gauge",
    "Robot Framework",
    "Appium",
    "XCTest",
    "Espresso",
    "UI Automator",
  ],
  "Architecture & Patterns": [
    "REST",
    "RESTful API",
    "SOAP",
    "API",
    "API Design",
    "API Gateway",
    "API Management",
    "Microservices",
    "Microservice Architecture",
    "Serverless",
    "Serverless Architecture",
    "FaaS",
    "Function as a Service",
    "Event-Driven Architecture",
    "EDA",
    "SOA",
    "Service-Oriented Architecture",
    "Monolithic Architecture",
    "Modular Monolith",
    "MVC",
    "Model-View-Controller",
    "MVVM",
    "Model-View-ViewModel",
    "MVP",
    "Model-View-Presenter",
    "Flux",
    "Redux",
    "OOP",
    "Object-Oriented Programming",
    "Functional Programming",
    "FP",
    "Reactive Programming",
    "Aspect-Oriented Programming",
    "AOP",
    "Design Patterns",
    "Singleton",
    "Factory",
    "Observer",
    "Strategy",
    "Decorator",
    "Adapter",
    "Facade",
    "Composite",
    "Command",
    "Iterator",
    "Mediator",
    "Proxy",
    "SOLID",
    "Single Responsibility Principle",
    "Open/Closed Principle",
    "Liskov Substitution Principle",
    "Interface Segregation Principle",
    "Dependency Inversion Principle",
    "DRY",
    "Don't Repeat Yourself",
    "KISS",
    "Keep It Simple, Stupid",
    "YAGNI",
    "You Aren't Gonna Need It",
    "DDD",
    "Domain-Driven Design",
    "TDD",
    "Test-Driven Development",
    "BDD",
    "Behavior-Driven Development",
    "Clean Architecture",
    "Hexagonal Architecture",
    "Ports and Adapters",
    "Onion Architecture",
    "Layered Architecture",
    "N-Tier Architecture",
    "Client-Server Architecture",
    "Peer-to-Peer Architecture",
    "P2P",
    "Distributed Systems",
    "Scalability",
    "High Availability",
    "Fault Tolerance",
    "Resilience",
    "Circuit Breaker",
    "Bulkhead",
    "Retry",
    "Timeout",
    "Fallback",
    "Cache",
    "Caching",
    "CDN",
    "Content Delivery Network",
    "Load Balancing",
    "Sharding",
    "Partitioning",
    "Replication",
    "Eventual Consistency",
    "ACID",
    "BASE",
    "CAP Theorem",
    "Saga Pattern",
    "CQRS",
    "Command Query Responsibility Segregation",
    "Event Sourcing",
  ],
  Security: [
    "OAuth",
    "OAuth 2.0",
    "OpenID Connect",
    "OIDC",
    "JWT",
    "JSON Web Token",
    "SAML",
    "Security Assertion Markup Language",
    "SSO",
    "Single Sign-On",
    "HTTPS",
    "SSL",
    "Secure Sockets Layer",
    "TLS",
    "Transport Layer Security",
    "Encryption",
    "Cryptography",
    "Symmetric Encryption",
    "Asymmetric Encryption",
    "Public Key Infrastructure",
    "PKI",
    "Digital Signatures",
    "Hashing",
    "Salting",
    "Bcrypt",
    "Scrypt",
    "Argon2",
    "PBKDF2",
    "Authentication",
    "Authorization",
    "Access Control",
    "RBAC",
    "Role-Based Access Control",
    "ABAC",
    "Attribute-Based Access Control",
    "MAC",
    "Mandatory Access Control",
    "DAC",
    "Discretionary Access Control",
    "Principle of Least Privilege",
    "Defense in Depth",
    "Zero Trust",
    "MFA",
    "Multi-Factor Authentication",
    "2FA",
    "Two-Factor Authentication",
    "Biometric Authentication",
    "OWASP",
    "OWASP Top 10",
    "OWASP ASVS",
    "OWASP ZAP",
    "Penetration Testing",
    "Pen Testing",
    "Security Audit",
    "Vulnerability Assessment",
    "Vulnerability Scanning",
    "Static Application Security Testing",
    "SAST",
    "Dynamic Application Security Testing",
    "DAST",
    "Interactive Application Security Testing",
    "IAST",
    "Runtime Application Self-Protection",
    "RASP",
    "Software Composition Analysis",
    "SCA",
    "Threat Modeling",
    "STRIDE",
    "DREAD",
    "Security Requirements",
    "Security Architecture",
    "Security Design",
    "Security Code Review",
    "Secure Coding",
    "Input Validation",
    "Output Encoding",
    "SQL Injection",
    "XSS",
    "Cross-Site Scripting",
    "CSRF",
    "Cross-Site Request Forgery",
    "SSRF",
    "Server-Side Request Forgery",
    "Command Injection",
    "Path Traversal",
    "File Inclusion",
    "XML External Entity",
    "XXE",
    "Insecure Deserialization",
    "Security Misconfiguration",
    "Sensitive Data Exposure",
    "Broken Authentication",
    "Broken Access Control",
    "Security Headers",
    "CSP",
    "Content Security Policy",
    "CORS",
    "Cross-Origin Resource Sharing",
    "HSTS",
    "HTTP Strict Transport Security",
    "Subresource Integrity",
    "SRI",
    "WAF",
    "Web Application Firewall",
    "IDS",
    "Intrusion Detection System",
    "IPS",
    "Intrusion Prevention System",
    "SIEM",
    "Security Information and Event Management",
    "SOC",
    "Security Operations Center",
    "Incident Response",
    "Forensics",
    "Digital Forensics",
    "Malware Analysis",
    "Reverse Engineering",
    "Secure SDLC",
    "DevSecOps",
    "Security Automation",
    "Compliance",
    "GDPR",
    "HIPAA",
    "PCI DSS",
    "SOX",
    "ISO 27001",
    "NIST",
    "CIS",
  ],
  "Data Science & AI": [
    "Machine Learning",
    "ML",
    "Deep Learning",
    "DL",
    "AI",
    "Artificial Intelligence",
    "NLP",
    "Natural Language Processing",
    "LLM",
    "Large Language Models",
    "GPT",
    "Generative AI",
    "GenAI",
    "Prompt Engineering",
    "Computer Vision",
    "CV",
    "Image Recognition",
    "Object Detection",
    "Semantic Segmentation",
    "OCR",
    "Optical Character Recognition",
    "Speech Recognition",
    "ASR",
    "Automatic Speech Recognition",
    "TTS",
    "Text-to-Speech",
    "Reinforcement Learning",
    "RL",
    "Neural Networks",
    "CNN",
    "Convolutional Neural Networks",
    "RNN",
    "Recurrent Neural Networks",
    "LSTM",
    "Long Short-Term Memory",
    "GRU",
    "Gated Recurrent Unit",
    "Transformer",
    "Attention Mechanism",
    "Transfer Learning",
    "Supervised Learning",
    "Unsupervised Learning",
    "Semi-Supervised Learning",
    "Self-Supervised Learning",
    "Clustering",
    "Classification",
    "Regression",
    "Anomaly Detection",
    "Recommendation Systems",
    "Recommender Systems",
    "Time Series Analysis",
    "Time Series Forecasting",
    "Feature Engineering",
    "Feature Selection",
    "Dimensionality Reduction",
    "PCA",
    "Principal Component Analysis",
    "t-SNE",
    "Ensemble Methods",
    "Random Forest",
    "Gradient Boosting",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "SVM",
    "Support Vector Machines",
    "KNN",
    "K-Nearest Neighbors",
    "Naive Bayes",
    "Decision Trees",
    "Linear Regression",
    "Logistic Regression",
    "K-means",
    "DBSCAN",
    "Hierarchical Clustering",
    "A/B Testing",
    "Hypothesis Testing",
    "Statistical Analysis",
    "Bayesian Statistics",
    "Frequentist Statistics",
    "Probability Theory",
    "Data Mining",
    "Data Wrangling",
    "Data Cleaning",
    "Data Preprocessing",
    "Data Visualization",
    "Data Analysis",
    "Exploratory Data Analysis",
    "EDA",
    "Big Data",
    "Data Warehouse",
    "ETL",
    "Extract, Transform, Load",
    "Data Lake",
    "Data Lakehouse",
    "Data Mesh",
    "Data Fabric",
    "Data Engineering",
    "Data Pipeline",
    "Data Modeling",
    "Data Architecture",
    "Data Governance",
    "Data Quality",
    "Data Catalog",
    "Data Lineage",
    "Data Observability",
    "Hadoop",
    "HDFS",
    "MapReduce",
    "Spark",
    "Apache Spark",
    "PySpark",
    "Spark Streaming",
    "Spark SQL",
    "Kafka",
    "Apache Kafka",
    "Kafka Streams",
    "Kafka Connect",
    "Flink",
    "Apache Flink",
    "Airflow",
    "Apache Airflow",
    "Dagster",
    "Prefect",
    "Luigi",
    "Argo Workflows",
    "Kubeflow",
    "MLflow",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "JAX",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Dash",
    "Streamlit",
    "Gradio",
    "Jupyter",
    "Jupyter Notebook",
    "JupyterLab",
    "Google Colab",
    "Databricks",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Athena",
    "Presto",
    "Trino",
    "Hive",
    "Pig",
    "HBase",
    "Cassandra",
    "MongoDB",
    "Neo4j",
    "Graph Databases",
    "Vector Databases",
    "Pinecone",
    "Weaviate",
    "Milvus",
    "Qdrant",
    "Chroma",
    "FAISS",
    "Embeddings",
    "Semantic Search",
    "RAG",
    "Retrieval Augmented Generation",
    "Fine-tuning",
    "Model Deployment",
    "Model Serving",
    "Model Monitoring",
    "MLOps",
    "ML Engineering",
    "AI Ethics",
    "Responsible AI",
    "Explainable AI",
    "XAI",
    "Fairness in AI",
    "Bias Detection",
    "AI Governance",
  ],
  "Web Servers & Protocols": [
    "Apache",
    "Apache HTTP Server",
    "Nginx",
    "IIS",
    "Internet Information Services",
    "Tomcat",
    "Apache Tomcat",
    "Jetty",
    "Caddy",
    "Lighttpd",
    "HTTP",
    "HTTP/1.1",
    "HTTP/2",
    "HTTP/3",
    "HTTPS",
    "WebSockets",
    "WebRTC",
    "Server-Sent Events",
    "SSE",
    "TCP/IP",
    "UDP",
    "DNS",
    "Domain Name System",
    "DHCP",
    "Dynamic Host Configuration Protocol",
    "FTP",
    "File Transfer Protocol",
    "SFTP",
    "SSH File Transfer Protocol",
    "FTPS",
    "SCP",
    "Secure Copy Protocol",
    "SMTP",
    "Simple Mail Transfer Protocol",
    "IMAP",
    "Internet Message Access Protocol",
    "POP3",
    "Post Office Protocol",
    "SNMP",
    "Simple Network Management Protocol",
    "LDAP",
    "Lightweight Directory Access Protocol",
    "Kerberos",
    "NTP",
    "Network Time Protocol",
    "SSH",
    "Secure Shell",
    "Telnet",
    "RDP",
    "Remote Desktop Protocol",
    "VNC",
    "Virtual Network Computing",
    "VPN",
    "Virtual Private Network",
    "IPsec",
    "Internet Protocol Security",
    "SSL/TLS",
    "Secure Sockets Layer/Transport Layer Security",
    "BGP",
    "Border Gateway Protocol",
    "OSPF",
    "Open Shortest Path First",
    "EIGRP",
    "Enhanced Interior Gateway Routing Protocol",
    "RIP",
    "Routing Information Protocol",
    "MPLS",
    "Multiprotocol Label Switching",
    "SDN",
    "Software-Defined Networking",
    "Load Balancing",
    "Reverse Proxy",
    "Forward Proxy",
    "CDN",
    "Content Delivery Network",
    "Edge Computing",
    "Caching",
    "HTTP Caching",
    "Browser Caching",
    "Server Caching",
    "Compression",
    "Gzip",
    "Brotli",
    "HTTP Headers",
    "CORS",
    "Cross-Origin Resource Sharing",
    "CSP",
    "Content Security Policy",
    "HSTS",
    "HTTP Strict Transport Security",
    "REST",
    "RESTful API",
    "GraphQL",
    "gRPC",
    "SOAP",
    "WebHooks",
    "WebSub",
    "MQTT",
    "Message Queuing Telemetry Transport",
    "AMQP",
    "Advanced Message Queuing Protocol",
    "STOMP",
    "Simple Text Oriented Messaging Protocol",
    "JMS",
    "Java Message Service",
    "RabbitMQ",
    "Apache Kafka",
    "Redis",
    "ZeroMQ",
    "NATS",
  ],
  "Networking & Cybersecurity": [
    "Network Security",
    "Network Architecture",
    "Network Design",
    "Network Engineering",
    "Network Administration",
    "Network Monitoring",
    "Network Troubleshooting",
    "Network Performance",
    "Network Optimization",
    "Network Automation",
    "Network Virtualization",
    "Network Protocols",
    "Routing",
    "Switching",
    "Firewalls",
    "Next-Generation Firewall",
    "NGFW",
    "WAF",
    "Web Application Firewall",
    "IDS",
    "Intrusion Detection System",
    "IPS",
    "Intrusion Prevention System",
    "SIEM",
    "Security Information and Event Management",
    "SOC",
    "Security Operations Center",
    "Vulnerability Management",
    "Vulnerability Assessment",
    "Penetration Testing",
    "Pen Testing",
    "Ethical Hacking",
    "Red Team",
    "Blue Team",
    "Purple Team",
    "Threat Hunting",
    "Threat Intelligence",
    "Malware Analysis",
    "Reverse Engineering",
    "Digital Forensics",
    "Incident Response",
    "DFIR",
    "Digital Forensics and Incident Response",
    "Security Architecture",
    "Security Engineering",
    "Security Compliance",
    "Security Governance",
    "Security Policies",
    "Security Awareness",
    "Security Training",
    "Risk Management",
    "Risk Assessment",
    "Disaster Recovery",
    "Business Continuity",
    "BCP",
    "Business Continuity Planning",
    "DRP",
    "Disaster Recovery Planning",
    "Cisco",
    "Cisco IOS",
    "Cisco ASA",
    "Cisco Firepower",
    "Cisco ACI",
    "Cisco DNA",
    "Cisco SD-WAN",
    "Cisco Meraki",
    "Juniper",
    "Juniper Junos",
    "Juniper SRX",
    "Palo Alto",
    "Palo Alto Networks",
    "Fortinet",
    "FortiGate",
    "Check Point",
    "Sophos",
    "SonicWall",
    "WatchGuard",
    "Barracuda",
    "F5",
    "F5 BIG-IP",
    "Citrix",
    "Citrix ADC",
    "Citrix NetScaler",
    "A10 Networks",
    "Arista",
    "Aruba",
    "HPE",
    "HP Enterprise",
    "Dell EMC",
    "VMware NSX",
    "VMware SD-WAN",
    "Wireshark",
    "Tcpdump",
    "Nmap",
    "Metasploit",
    "Burp Suite",
    "OWASP ZAP",
    "Kali Linux",
    "ParrotOS",
    "BlackArch",
    "Snort",
    "Suricata",
    "Zeek",
    "Bro",
    "Splunk",
    "ELK Stack",
    "Elasticsearch",
    "Logstash",
    "Kibana",
    "Graylog",
    "QRadar",
    "ArcSight",
    "AlienVault",
    "OSSIM",
    "Tenable",
    "Nessus",
    "Qualys",
    "Rapid7",
    "Nexpose",
    "InsightVM",
    "OpenVAS",
    "CrowdStrike",
    "Carbon Black",
    "Symantec",
    "McAfee",
    "Trend Micro",
    "Kaspersky",
    "Bitdefender",
    "Cylance",
    "SentinelOne",
    "Darktrace",
    "Vectra",
    "ExtraHop",
    "Cisco Umbrella",
    "Zscaler",
    "Okta",
    "Ping Identity",
    "ForgeRock",
    "CyberArk",
    "BeyondTrust",
    "HashiCorp Vault",
    "KeePass",
    "LastPass",
    "1Password",
    "Bitwarden",
    "CISSP",
    "Certified Information Systems Security Professional",
    "CEH",
    "Certified Ethical Hacker",
    "CISM",
    "Certified Information Security Manager",
    "CISA",
    "Certified Information Systems Auditor",
    "Security+",
    "CompTIA Security+",
    "Network+",
    "CompTIA Network+",
    "CCNA",
    "Cisco Certified Network Associate",
    "CCNP",
    "Cisco Certified Network Professional",
    "CCIE",
    "Cisco Certified Internetwork Expert",
    "JNCIA",
    "Juniper Networks Certified Internet Associate",
    "JNCIS",
    "Juniper Networks Certified Internet Specialist",
    "JNCIP",
    "Juniper Networks Certified Internet Professional",
    "JNCIE",
    "Juniper Networks Certified Internet Expert",
    "OSCP",
    "Offensive Security Certified Professional",
    "OSCE",
    "Offensive Security Certified Expert",
    "GIAC",
    "Global Information Assurance Certification",
    "SANS",
    "SysAdmin, Audit, Network, and Security",
  ],
  "IT Support & System Administration": [
    "IT Support",
    "Technical Support",
    "Help Desk",
    "Service Desk",
    "Desktop Support",
    "System Administration",
    "SysAdmin",
    "Systems Engineer",
    "IT Operations",
    "IT Infrastructure",
    "IT Management",
    "IT Service Management",
    "ITSM",
    "ITIL",
    "Information Technology Infrastructure Library",
    "Change Management",
    "Incident Management",
    "Problem Management",
    "Service Level Agreement",
    "SLA",
    "Operating Systems",
    "Windows",
    "Windows Server",
    "Windows 10",
    "Windows 11",
    "Active Directory",
    "AD",
    "Group Policy",
    "GPO",
    "LDAP",
    "Lightweight Directory Access Protocol",
    "Linux",
    "Ubuntu",
    "Debian",
    "CentOS",
    "Red Hat",
    "RHEL",
    "Red Hat Enterprise Linux",
    "Fedora",
    "SUSE",
    "Arch Linux",
    "Kali Linux",
    "Unix",
    "macOS",
    "Shell Scripting",
    "Bash",
    "PowerShell",
    "Python",
    "Perl",
    "Virtualization",
    "VMware",
    "VMware vSphere",
    "VMware ESXi",
    "VMware vCenter",
    "Hyper-V",
    "VirtualBox",
    "KVM",
    "Xen",
    "Proxmox",
    "Containerization",
    "Docker",
    "Kubernetes",
    "K8s",
    "LXC",
    "LXD",
    "Cloud Computing",
    "AWS",
    "Amazon Web Services",
    "Azure",
    "Microsoft Azure",
    "GCP",
    "Google Cloud Platform",
    "Cloud Migration",
    "Hybrid Cloud",
    "Multi-Cloud",
    "IaaS",
    "Infrastructure as a Service",
    "PaaS",
    "Platform as a Service",
    "SaaS",
    "Software as a Service",
    "Backup",
    "Backup and Recovery",
    "Disaster Recovery",
    "Business Continuity",
    "Veeam",
    "Acronis",
    "Commvault",
    "Veritas",
    "NetBackup",
    "Storage",
    "SAN",
    "Storage Area Network",
    "NAS",
    "Network Attached Storage",
    "DAS",
    "Direct Attached Storage",
    "RAID",
    "Redundant Array of Independent Disks",
    "iSCSI",
    "Fibre Channel",
    "FC",
    "Software-Defined Storage",
    "SDS",
    "EMC",
    "Dell EMC",
    "NetApp",
    "HPE",
    "HP Enterprise",
    "IBM",
    "Hitachi",
    "Pure Storage",
    "Monitoring",
    "System Monitoring",
    "Infrastructure Monitoring",
    "Application Monitoring",
    "Performance Monitoring",
    "Nagios",
    "Zabbix",
    "PRTG",
    "SolarWinds",
    "Datadog",
    "New Relic",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Elasticsearch",
    "Logstash",
    "Kibana",
    "Splunk",
    "Graylog",
    "Automation",
    "IT Automation",
    "Infrastructure Automation",
    "Configuration Management",
    "Ansible",
    "Puppet",
    "Chef",
    "Salt",
    "SaltStack",
    "Terraform",
    "CloudFormation",
    "Scripting",
    "Patch Management",
    "WSUS",
    "Windows Server Update Services",
    "SCCM",
    "System Center Configuration Manager",
    "Microsoft Endpoint Manager",
    "Intune",
    "Microsoft Intune",
    "MDM",
    "Mobile Device Management",
    "Email",
    "Exchange",
    "Exchange Server",
    "Exchange Online",
    "Office 365",
    "Microsoft 365",
    "Google Workspace",
    "G Suite",
    "Zimbra",
    "Postfix",
    "Sendmail",
    "SMTP",
    "Simple Mail Transfer Protocol",
    "POP3",
    "Post Office Protocol",
    "IMAP",
    "Internet Message Access Protocol",
    "Collaboration",
    "Microsoft Teams",
    "Slack",
    "Zoom",
    "WebEx",
    "Google Meet",
    "SharePoint",
    "OneDrive",
    "Google Drive",
    "Dropbox",
    "Box",
    "Ticketing Systems",
    "ServiceNow",
    "Jira Service Desk",
    "Zendesk",
    "Freshdesk",
    "ManageEngine ServiceDesk Plus",
    "BMC Remedy",
    "Cherwell",
    "Spiceworks",
    "Networking",
    "LAN",
    "Local Area Network",
    "WAN",
    "Wide Area Network",
    "WLAN",
    "Wireless LAN",
    "Wi-Fi",
    "Ethernet",
    "TCP/IP",
    "DHCP",
    "Dynamic Host Configuration Protocol",
    "DNS",
    "Domain Name System",
    "VPN",
    "Virtual Private Network",
    "Routing",
    "Switching",
    "Firewalls",
    "Load Balancing",
    "Cisco",
    "Juniper",
    "Aruba",
    "Ubiquiti",
    "Meraki",
    "Certification",
    "CompTIA A+",
    "CompTIA Network+",
    "CompTIA Security+",
    "CompTIA Server+",
    "CompTIA Cloud+",
    "CompTIA Linux+",
    "Microsoft Certified",
    "MCSA",
    "Microsoft Certified Solutions Associate",
    "MCSE",
    "Microsoft Certified Solutions Expert",
    "MCP",
    "Microsoft Certified Professional",
    "RHCSA",
    "Red Hat Certified System Administrator",
    "RHCE",
    "Red Hat Certified Engineer",
    "CCNA",
    "Cisco Certified Network Associate",
    "ITIL",
    "ITIL Foundation",
    "AWS Certified",
    "Azure Certified",
    "Google Cloud Certified",
  ],
}

// Flatten the technical skills map for easier lookup
export const technicalSkills = Object.values(technicalSkillsMap).flat().sort()

// Soft skills organized by category
export const softSkillsMap: Record<string, string[]> = {
  "Communication & Interpersonal": [
    "Communication",
    "Interpersonal",
    "Presentation",
    "Public Speaking",
    "Writing",
    "Listening",
    "Negotiation",
    "Persuasion",
    "Conflict Resolution",
    "Diplomacy",
    "Empathy",
    "Emotional Intelligence",
  ],
  "Teamwork & Collaboration": [
    "Teamwork",
    "Collaboration",
    "Team Player",
    "Cooperative",
    "Cross-functional",
    "Relationship Building",
    "Networking",
    "Partnership",
    "Mentoring",
    "Coaching",
    "Training",
  ],
  "Problem Solving & Critical Thinking": [
    "Problem-Solving",
    "Critical Thinking",
    "Analytical",
    "Analysis",
    "Troubleshooting",
    "Debugging",
    "Decision-Making",
    "Judgment",
    "Reasoning",
    "Logic",
    "Strategic Thinking",
    "Systems Thinking",
  ],
  "Work Ethic & Attitude": [
    "Self-Motivated",
    "Initiative",
    "Proactive",
    "Driven",
    "Ambitious",
    "Dedicated",
    "Committed",
    "Reliable",
    "Dependable",
    "Punctual",
    "Responsible",
    "Accountable",
    "Ethical",
    "Integrity",
    "Honest",
  ],
  "Adaptability & Flexibility": [
    "Adaptability",
    "Flexibility",
    "Versatility",
    "Agility",
    "Resilience",
    "Open-Minded",
    "Willingness to Learn",
    "Growth Mindset",
    "Continuous Learning",
    "Curiosity",
  ],
  "Organization & Time Management": [
    "Organization",
    "Organizational",
    "Time Management",
    "Planning",
    "Prioritization",
    "Multi-tasking",
    "Detail-Oriented",
    "Thorough",
    "Meticulous",
    "Efficient",
    "Productivity",
  ],
  "Leadership & Management": [
    "Leadership",
    "Management",
    "Supervision",
    "Delegation",
    "Motivation",
    "Inspiration",
    "Influence",
    "Direction",
    "Guidance",
    "Visionary",
    "Strategic",
    "Executive",
  ],
  "Creativity & Innovation": [
    "Creativity",
    "Creative",
    "Innovation",
    "Innovative",
    "Originality",
    "Original",
    "Imagination",
    "Inventive",
    "Design Thinking",
    "Brainstorming",
    "Ideation",
  ],
  "Customer & Service Orientation": [
    "Customer-Focused",
    "Customer Service",
    "Client Relations",
    "User-Centered",
    "Patient",
    "Empathetic",
    "Responsive",
    "Attentive",
    "Supportive",
  ],
  "Project & Task Management": [
    "Project Management",
    "Task Management",
    "Coordination",
    "Execution",
    "Implementation",
    "Follow-through",
    "Delivery",
    "Results-Oriented",
    "Goal-Oriented",
    "Achievement",
  ],
  "Stress Management": [
    "Stress Management",
    "Pressure Handling",
    "Calm",
    "Composed",
    "Poised",
    "Level-Headed",
    "Balanced",
    "Mindful",
    "Self-Aware",
    "Self-Control",
  ],
}

// Flatten the soft skills map for easier lookup
export const softSkills = Object.values(softSkillsMap).flat().sort()

// Requirements organized by category
export const requirementsMap: Record<string, string[]> = {
  Education: [
    "Bachelor's",
    "Master's",
    "MBA",
    "PhD",
    "Doctorate",
    "Degree",
    "Diploma",
    "Certificate",
    "Certification",
    "Licensed",
    "Accredited",
    "Graduate",
    "Undergraduate",
  ],
  Experience: [
    "1+ years",
    "2+ years",
    "3+ years",
    "4+ years",
    "5+ years",
    "7+ years",
    "10+ years",
    "Years of experience",
    "Experienced",
    "Seasoned",
    "Veteran",
    "Junior",
    "Mid-level",
    "Senior",
    "Lead",
    "Principal",
    "Expert",
    "Specialist",
    "Professional",
  ],
  "Work Arrangements": [
    "Remote",
    "Hybrid",
    "On-site",
    "In-office",
    "Telecommute",
    "Work from Home",
    "Flexible",
    "Relocation",
    "Travel",
    "International",
    "Domestic",
    "Local",
  ],
  "Employment Type": [
    "Full-time",
    "Part-time",
    "Contract",
    "Contractor",
    "Freelance",
    "Permanent",
    "Temporary",
    "Seasonal",
    "Internship",
    "Co-op",
    "Apprenticeship",
  ],
  "Career Level": [
    "Entry-level",
    "Junior",
    "Mid-level",
    "Senior",
    "Lead",
    "Manager",
    "Director",
    "Executive",
    "C-level",
    "VP",
    "Head of",
    "Chief",
  ],
  "Clearance & Background": [
    "Security Clearance",
    "Background Check",
    "Drug Test",
    "Criminal Record Check",
    "Reference Check",
    "Credit Check",
    "Screening",
  ],
  "Specific Requirements": [
    "Required",
    "Mandatory",
    "Essential",
    "Must-have",
    "Preferred",
    "Desired",
    "Nice-to-have",
    "Bonus",
    "Plus",
    "Advantage",
  ],
  Qualifications: [
    "Qualified",
    "Proficient",
    "Skilled",
    "Competent",
    "Capable",
    "Knowledgeable",
    "Familiar",
    "Understanding",
    "Expertise",
    "Mastery",
    "Fluent",
    "Native",
  ],
  "Specific Phrases": [
    "Ability to",
    "Capable of",
    "Responsible for",
    "Accountable for",
    "Experience with",
    "Experience in",
    "Knowledge of",
    "Understanding of",
    "Familiarity with",
    "Proficiency in",
    "Expertise in",
    "Industry experience",
    "Strong understanding",
    "Good understanding",
  ],
}

// Flatten the requirements map for easier lookup
export const requirements = Object.values(requirementsMap).flat().sort()

export const normalizeSkillName = (skill: string): string => {
  return skill
    .trim()
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .replace(/\s+/g, " ")
    .toLowerCase()
}

export const stopwords = [
  // English stopwords
  "ability",
  "able",
  "about",
  "above",
  "abroad",
  "according",
  "accordingly",
  "across",
  "actually",
  "adj",
  "after",
  "afterwards",
  "again",
  "against",
  "ago",
  "ahead",
  "ain't",
  "all",
  "allow",
  "allows",
  "almost",
  "alone",
  "along",
  "alongside",
  "already",
  "also",
  "although",
  "always",
  "am",
  "amid",
  "amidst",
  "among",
  "amongst",
  "an",
  "and",
  "another",
  "any",
  "anybody",
  "anyhow",
  "anyone",
  "anything",
  "anyway",
  "anyways",
  "anywhere",
  "apart",
  "appear",
  "appreciate",
  "appropriate",
  "are",
  "aren't",
  "around",
  "as",
  "a's",
  "aside",
  "ask",
  "asking",
  "associated",
  "at",
  "available",
  "away",
  "awfully",
  "be",
  "became",
  "because",
  "become",
  "becomes",
  "becoming",
  "been",
  "before",
  "beforehand",
  "begin",
  "behind",
  "being",
  "believe",
  "below",
  "beside",
  "besides",
  "best",
  "better",
  "between",
  "beyond",
  "both",
  "brief",
  "but",
  "by",
  "came",
  "can",
  "cannot",
  "cant",
  "can't",
  "caption",
  "cause",
  "causes",
  "certain",
  "certainly",
  "changes",
  "clearly",
  "c'mon",
  "co",
  "co.",
  "com",
  "come",
  "comes",
  "coming",
  "commonly",
  "compare",
  "completely",
  "concerning",
  "consequently",
  "consider",
  "considering",
  "contain",
  "containing",
  "contains",
  "corresponding",
  "could",
  "couldn't",
  "course",
  "currently",
  "definitely",
  "described",
  "despite",
  "did",
  "didn't",
  "different",
  "directly",
  "do",
  "does",
  "doesn't",
  "doing",
  "done",
  "don't",
  "down",
  "downwards",
  "during",
  "each",
  "edu",
  "eg",
  "eight",
  "either",
  "else",
  "elsewhere",
  "enough",
  "entirely",
  "especially",
  "et",
  "etc",
  "even",
  "ever",
  "every",
  "everybody",
  "everyone",
  "everything",
  "everywhere",
  "ex",
  "exactly",
  "example",
  "except",
  "fairly",
  "far",
  "few",
  "fewer",
  "fifth",
  "first",
  "five",
  "followed",
  "following",
  "follows",
  "for",
  "forever",
  "former",
  "formerly",
  "forth",
  "forward",
  "found",
  "four",
  "from",
  "further",
  "furthermore",
  "get",
  "gets",
  "getting",
  "given",
  "gives",
  "go",
  "goes",
  "going",
  "gone",
  "got",
  "gotten",
  "greetings",
  "had",
  "hadn't",
  "half",
  "happens",
  "hardly",
  "has",
  "hasn't",
  "have",
  "haven't",
  "having",
  "he",
  "he'd",
  "he'll",
  "hello",
  "help",
  "hence",
  "her",
  "here",
  "hereafter",
  "hereby",
  "herein",
  "here's",
  "hereupon",
  "hers",
  "herself",
  "he's",
  "hi",
  "him",
  "himself",
  "his",
  "hither",
  "hopefully",
  "how",
  "howbeit",
  "however",
  "how's",
  "i",
  "i'd",
  "ie",
  "if",
  "ignored",
  "i'll",
  "i'm",
  "immediate",
  "in",
  "inasmuch",
  "inc",
  "indeed",
  "indicate",
  "indicated",
  "indicates",
  "inner",
  "inside",
  "insofar",
  "instead",
  "into",
  "inward",
  "is",
  "isn't",
  "it",
  "it'd",
  "it'll",
  "its",
  "it's",
  "itself",
  "i've",
  "just",
  "keep",
  "keeps",
  "kept",
  "know",
  "known",
  "knows",
  "last",
  "lately",
  "later",
  "latter",
  "latterly",
  "least",
  "less",
  "lest",
  "let",
  "let's",
  "like",
  "liked",
  "likely",
  "likewise",
  "little",
  "look",
  "looking",
  "looks",
  "ltd",
  "mainly",
  "many",
  "may",
  "maybe",
  "me",
  "mean",
  "meanwhile",
  "merely",
  "might",
  "more",
  "moreover",
  "most",
  "mostly",
  "much",
  "must",
  "my",
  "myself",
  "name",
  "namely",
  "nd",
  "near",
  "nearly",
  "necessary",
  "need",
  "needs",
  "neither",
  "never",
  "nevertheless",
  "new",
  "next",
  "nine",
  "no",
  "nobody",
  "non",
  "none",
  "nonetheless",
  "noone",
  "nor",
  "normally",
  "not",
  "nothing",
  "novel",
  "now",
  "nowhere",
  "obviously",
  "of",
  "off",
  "often",
  "oh",
  "ok",
  "okay",
  "old",
  "on",
  "once",
  "one",
  "ones",
  "one's",
  "only",
  "onto",
  "opposite",
  "or",
  "other",
  "others",
  "otherwise",
  "ought",
  "our",
  "ours",
  "ourselves",
  "out",
  "outside",
  "over",
  "overall",
  "own",
  "particular",
  "particularly",
  "perhaps",
  "placed",
  "please",
  "plus",
  "possible",
  "presumably",
  "probably",
  "provided",
  "provides",
  "que",
  "quite",
  "qv",
  "rather",
  "rd",
  "re",
  "really",
  "reasonably",
  "regarding",
  "regardless",
  "regards",
  "relatively",
  "respectively",
  "right",
  "round",
  "said",
  "same",
  "saw",
  "say",
  "saying",
  "says",
  "second",
  "secondly",
  "see",
  "seeing",
  "seem",
  "seemed",
  "seeming",
  "seems",
  "seen",
  "self",
  "selves",
  "sensible",
  "sent",
  "serious",
  "seriously",
  "seven",
  "several",
  "shall",
  "she",
  "she'd",
  "she'll",
  "she's",
  "should",
  "shouldn't",
  "since",
  "six",
  "so",
  "some",
  "somebody",
  "someday",
  "somehow",
  "someone",
  "something",
  "sometime",
  "sometimes",
  "somewhat",
  "somewhere",
  "soon",
  "sorry",
  "specified",
  "specify",
  "specifying",
  "still",
  "sub",
  "such",
  "sup",
  "sure",
  "take",
  "taken",
  "taking",
  "tell",
  "tends",
  "th",
  "than",
  "thank",
  "thanks",
  "thanx",
  "that",
  "that'll",
  "thats",
  "that's",
  "that've",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "thence",
  "there",
  "thereafter",
  "thereby",
  "there'd",
  "therefore",
  "therein",
  "there'll",
  "there's",
  "theres",
  "thereupon",
  "there've",
  "these",
  "they",
  "they'd",
  "they'll",
  "they're",
  "they've",
  "thing",
  "things",
  "think",
  "third",
  "thirty",
  "this",
  "thorough",
  "thoroughly",
  "those",
  "though",
  "three",
  "through",
  "throughout",
  "thru",
  "thus",
  "till",
  "to",
  "together",
  "too",
  "took",
  "toward",
  "towards",
  "tried",
  "tries",
  "truly",
  "try",
  "trying",
  "t's",
  "twice",
  "two",
  "un",
  "under",
  "underneath",
  "undoing",
  "unfortunately",
  "unless",
  "unlike",
  "unlikely",
  "until",
  "unto",
  "up",
  "upon",
  "upwards",
  "us",
  "use",
  "used",
  "useful",
  "uses",
  "using",
  "usually",
  "v",
  "value",
  "various",
  "very",
  "via",
  "viz",
  "vs",
  "want",
  "wants",
  "was",
  "wasn't",
  "way",
  "we",
  "we'd",
  "welcome",
  "well",
  "we'll",
  "went",
  "were",
  "weren't",
  "we've",
  "what",
  "whatever",
  "what'll",
  "what's",
  "what've",
  "when",
  "whence",
  "whenever",
  "when's",
  "where",
  "whereafter",
  "whereas",
  "whereby",
  "wherein",
  "where's",
  "whereupon",
  "wherever",
  "whether",
  "which",
  "whichever",
  "while",
  "whilst",
  "whither",
  "who",
  "who'd",
  "whoever",
  "whole",
  "who'll",
  "whom",
  "whomever",
  "who's",
  "whose",
  "why",
  "why's",
  "will",
  "willing",
  "wish",
  "with",
  "within",
  "without",
  "wonder",
  "won't",
  "would",
  "wouldn't",
  "yes",
  "yet",
  "you",
  "you'd",
  "you'll",
  "your",
  "you're",
  "yours",
  "yourself",
  "yourselves",
  "you've",
  "zero",

  // Spanish stopwords
  "a",
  "al",
  "algo",
  "algunas",
  "algunos",
  "ante",
  "antes",
  "como",
  "con",
  "contra",
  "cual",
  "cuando",
  "de",
  "del",
  "desde",
  "donde",
  "durante",
  "e",
  "el",
  "ella",
  "ellas",
  "ellos",
  "en",
  "entre",
  "era",
  "erais",
  "eran",
  "eras",
  "eres",
  "es",
  "esa",
  "esas",
  "ese",
  "eso",
  "esos",
  "esta",
  "estaba",
  "estabais",
  "estaban",
  "estabas",
  "estad",
  "estada",
  "estadas",
  "estado",
  "estados",
  "estamos",
  "estando",
  "estar",
  "estaremos",
  "estará",
  "estarán",
  "estarás",
  "estaré",
  "estaréis",
  "estaría",
  "estaríais",
  "estaríamos",
  "estarían",
  "estarías",
  "estas",
  "este",
  "estemos",
  "esto",
  "estos",
  "estoy",
  "estuve",
  "estuviera",
  "estuvierais",
  "estuvieran",
  "estuvieras",
  "estuvieron",
  "estuviese",
  "estuvieseis",
  "estuviesen",
  "estuvieses",
  "estuvimos",
  "estuviste",
  "estuvisteis",
  "estuviéramos",
  "estuviésemos",
  "estuvo",
  "está",
  "estábamos",
  "estáis",
  "están",
  "estás",
  "esté",
  "estéis",
  "estén",
  "estés",
  "fue",
  "fuera",
  "fuerais",
  "fueran",
  "fueras",
  "fueron",
  "fuese",
  "fueseis",
  "fuesen",
  "fueses",
  "fui",
  "fuimos",
  "fuiste",
  "fuisteis",
  "fuéramos",
  "fuésemos",
  "ha",
  "habida",
  "habidas",
  "habido",
  "habidos",
  "habiendo",
  "habremos",
  "habrá",
  "habrán",
  "habrás",
  "habré",
  "habréis",
  "habría",
  "habríais",
  "habríamos",
  "habrían",
  "habrías",
  "habéis",
  "había",
  "habíais",
  "habíamos",
  "habían",
  "habías",
  "han",
  "has",
  "hasta",
  "hay",
  "haya",
  "hayamos",
  "hayan",
  "hayas",
  "hayáis",
  "he",
  "hemos",
  "hube",
  "hubiera",
  "hubierais",
  "hubieran",
  "hubieras",
  "hubieron",
  "hubiese",
  "hubieseis",
  "hubiesen",
  "hubieses",
  "hubimos",
  "hubiste",
  "hubisteis",
  "hubiéramos",
  "hubiésemos",
  "hubo",
  "la",
  "las",
  "le",
  "les",
  "lo",
  "los",
  "me",
  "mi",
  "mis",
  "mucho",
  "muchos",
  "muy",
  "más",
  "mí",
  "mía",
  "mías",
  "mío",
  "míos",
  "nada",
  "ni",
  "no",
  "nos",
  "nosotras",
  "nosotros",
  "nuestra",
  "nuestras",
  "nuestro",
  "nuestros",
  "o",
  "os",
  "otra",
  "otras",
  "otro",
  "otros",
  "para",
  "pero",
  "poco",
  "por",
  "porque",
  "que",
  "quien",
  "quienes",
  "qué",
  "se",
  "sea",
  "seamos",
  "sean",
  "seas",
  "seremos",
  "será",
  "serán",
  "serás",
  "seré",
  "seréis",
  "sería",
  "seríais",
  "seríamos",
  "serían",
  "serías",
  "seáis",
  "si",
  "sido",
  "siendo",
  "sin",
  "sobre",
  "sois",
  "somos",
  "son",
  "soy",
  "su",
  "sus",
  "suya",
  "suyas",
  "suyo",
  "suyos",
  "sí",
  "también",
  "tanto",
  "te",
  "tendremos",
  "tendrá",
  "tendrán",
  "tendrás",
  "tendré",
  "tendréis",
  "tendría",
  "tendríais",
  "tendríamos",
  "tendrían",
  "tendrías",
  "tened",
  "tenemos",
  "tenga",
  "tengamos",
  "tengan",
  "tengas",
  "tengo",
  "tengáis",
  "tenida",
  "tenidas",
  "tenido",
  "tenidos",
  "teniendo",
  "tenéis",
  "tenía",
  "teníais",
  "teníamos",
  "tenían",
  "tenías",
  "ti",
  "tiene",
  "tienen",
  "tienes",
  "todo",
  "todos",
  "tu",
  "tus",
  "tuve",
  "tuviera",
  "tuvierais",
  "tuvieran",
  "tuvieras",
  "tuvieron",
  "tuviese",
  "tuvieseis",
  "tuviesen",
  "tuvieses",
  "tuvimos",
  "tuviste",
  "tuvisteis",
  "tuviéramos",
  "tuviésemos",
  "tuvo",
  "tuya",
  "tuyas",
  "tuyo",
  "tuyos",
  "tú",
  "un",
  "una",
  "uno",
  "unos",
  "vosotras",
  "vosotros",
  "vuestra",
  "vuestras",
  "vuestro",
  "vuestros",
  "y",
  "ya",
  "yo",
  "él",
  "éramos",

  // Spanish job description specific words
  "actualmente",
  "buscaremos",
  "desarrollador",
  "junior",
  "como",
  "colaborar",
  "desarrollar",
  "identificar",
  "participar",
  "mantenerte",
  "buscamos",
  "buen",
  "conocimiento",
  "capacidad",
  "trabajo",
  "compensaci",
  "usd",
  "hardware",
  "horarios",
  "licencias",
  "ambiente",
  "oportunidades",
  "llevamos",
  "liderando",
  "contamos",
  "conformado",
  "postularte",
  "vacante",
  "estarás",
  "dando",
  "primer",
  "paso",
  "proceso",
  "convencional",
  "profundidad",
  "habilidades",
  "intereses",
  "expectativas",
  "objetivo",
  "realizar",
  "búsqueda",
  "personalizada",
  "encontrar",
  "ideal",
  "harás",
  "centrándote",
  "escribir",
  "código",
  "limpio",
  "eficiente",
  "contribuyendo",
  "diferentes",
  "etapas",
  "ciclo",
  "vida",
  "solucionar",
  "errores",
  "implementación",
  "soluciones",
  "optimizaciones",
  "revisiones",
  "mantener",
  "alta",
  "calidad",
  "aprender",
  "mejores",
  "prácticas",
  "actualizado",
  "nuevos",
  "frameworks",
  "bibliotecas",
  "entendiendo",
  "incorporarlos",
  "proyectos",
  "reuniones",
  "debates",
  "equipo",
  "aportando",
  "ideas",
  "comentarios",
  "mejorar",
  "desarrollo",
  "proyecto",
  "entendimiento",
  "algoritmos",
  "básicos",
  "estructuras",
  "datos",
  "básico",
  "sistemas",
  "control",
  "versiones",
  "preferiblemente",
  "resolver",
  "problemas",
  "forma",
  "eficaz",
  "nuevas",
  "tecnologías",
  "rápidamente",
  "nivel",
  "inglés",
  "ofrecemos",
  "seja",
  "mais",
  "fácil",
  "remoto",
  "trabaja",
  "casa",
  "donde",
  "quieras",
  "moneda",
  "local",
  "prefieras",
  "media",
  "mercado",
  "flexibles",
  "mater",
  "paternidad",
  "vacaciones",
  "días",
  "festivos",
  "nacionales",
  "pagos",
  "laboral",
  "multicultural",
  "innovador",
  "perfecto",
  "hacer",
  "amigos",
  "colaborar",
  "personas",
  "talentosas",
  "mundo",
  "crecimiento",
  "profesional",
  "través",
  "mentorías",
  "entrenamientos",
]

export const isValidSkill = (term: string): boolean => {
  const normalized = term.toLowerCase().trim()

  if (stopwords.includes(normalized)) {
    return false
  }

  if (normalized.length < 2) {
    return false
  }

  if (/^\d+$/.test(normalized)) {
    return false
  }

  return true
}
