/**
 * Curated lists of skills and requirements for job analysis
 */

// Technical skills organized by category
export const technicalSkillsMap: Record<string, string[]> = {
  "Programming Languages": [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "PHP",
    "Ruby",
    "Go",
    "Golang",
    "Swift",
    "Kotlin",
    "Rust",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Shell",
    "Bash",
    "PowerShell",
  ],
  "Web Technologies": [
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "SASS",
    "SCSS",
    "Less",
    "Bootstrap",
    "Tailwind",
    "Material UI",
    "React",
    "Angular",
    "Vue",
    "Svelte",
    "jQuery",
    "Redux",
    "Next.js",
    "Gatsby",
    "Nuxt",
    "Express",
    "Node.js",
    "Deno",
    "Electron",
    "PWA",
  ],
  "Frameworks & Libraries": [
    "Laravel",
    "Django",
    "Flask",
    "Spring",
    "ASP.NET",
    "Rails",
    "Symfony",
    "CodeIgniter",
    "Struts",
    "Hibernate",
    "Entity Framework",
    "NestJS",
    "FastAPI",
    "Pandas",
    "NumPy",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
  ],
  Databases: [
    "SQL",
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "SQLite",
    "MongoDB",
    "Cassandra",
    "Redis",
    "DynamoDB",
    "Elasticsearch",
    "Neo4j",
    "MariaDB",
    "Firebase",
    "Firestore",
    "Supabase",
    "CouchDB",
    "GraphQL",
  ],
  "Cloud & DevOps": [
    "AWS",
    "Azure",
    "GCP",
    "Google Cloud",
    "Heroku",
    "Netlify",
    "Vercel",
    "Docker",
    "Kubernetes",
    "K8s",
    "CI/CD",
    "Jenkins",
    "Travis",
    "CircleCI",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "Puppet",
    "Chef",
    "Prometheus",
    "Grafana",
  ],
  "Tools & Version Control": [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Mercurial",
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Monday",
    "Notion",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Photoshop",
    "Illustrator",
  ],
  "Microsoft Technologies": [
    ".NET",
    ".NET Core",
    "ASP.NET",
    "WPF",
    "WCF",
    "LINQ",
    "SharePoint",
    "Dynamics 365",
    "Power BI",
    "Power Apps",
    "Power Automate",
    "Office 365",
    "Azure DevOps",
  ],
  Mobile: [
    "Android",
    "iOS",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Cordova",
    "SwiftUI",
    "UIKit",
    "Kotlin",
    "Objective-C",
    "Dart",
  ],
  Testing: [
    "Jest",
    "Mocha",
    "Chai",
    "Jasmine",
    "Cypress",
    "Selenium",
    "Puppeteer",
    "JUnit",
    "NUnit",
    "xUnit",
    "TestNG",
    "PHPUnit",
    "RSpec",
    "Pytest",
    "TDD",
    "BDD",
    "Unit Testing",
    "Integration Testing",
    "E2E Testing",
  ],
  "Architecture & Patterns": [
    "REST",
    "SOAP",
    "API",
    "Microservices",
    "Serverless",
    "MVC",
    "MVVM",
    "OOP",
    "Functional Programming",
    "Design Patterns",
    "SOLID",
    "DRY",
    "KISS",
    "DDD",
  ],
  Security: [
    "OAuth",
    "JWT",
    "SAML",
    "SSO",
    "HTTPS",
    "SSL",
    "TLS",
    "Encryption",
    "Authentication",
    "Authorization",
    "OWASP",
    "Penetration Testing",
    "Security Audit",
    "Vulnerability Assessment",
  ],
  "Data Science & AI": [
    "Machine Learning",
    "Deep Learning",
    "AI",
    "Artificial Intelligence",
    "NLP",
    "Natural Language Processing",
    "Computer Vision",
    "Data Mining",
    "Big Data",
    "Data Warehouse",
    "ETL",
    "Data Lake",
    "Hadoop",
    "Spark",
    "Kafka",
  ],
  "Web Servers & Protocols": [
    "Apache",
    "Nginx",
    "IIS",
    "HTTP",
    "HTTPS",
    "WebSockets",
    "TCP/IP",
    "DNS",
    "FTP",
    "SMTP",
    "IMAP",
    "POP3",
  ],
}

// Flatten the technical skills map for easier lookup
export const technicalSkills = Object.values(technicalSkillsMap).flat()

// Soft skills organized by category
export const softSkillsMap: Record<string, string[]> = {
  "Communication & Interpersonal": [
    "Communication",
    "Interpersonal",
    "Presentation",
    "Public Speaking",
    "Writing",
    "Listening",
    "Negotiation",
    "Persuasion",
    "Conflict Resolution",
    "Diplomacy",
    "Empathy",
    "Emotional Intelligence",
  ],
  "Teamwork & Collaboration": [
    "Teamwork",
    "Collaboration",
    "Team Player",
    "Cooperative",
    "Cross-functional",
    "Relationship Building",
    "Networking",
    "Partnership",
    "Mentoring",
    "Coaching",
    "Training",
  ],
  "Problem Solving & Critical Thinking": [
    "Problem-Solving",
    "Critical Thinking",
    "Analytical",
    "Analysis",
    "Troubleshooting",
    "Debugging",
    "Decision-Making",
    "Judgment",
    "Reasoning",
    "Logic",
    "Strategic Thinking",
    "Systems Thinking",
  ],
  "Work Ethic & Attitude": [
    "Self-Motivated",
    "Initiative",
    "Proactive",
    "Driven",
    "Ambitious",
    "Dedicated",
    "Committed",
    "Reliable",
    "Dependable",
    "Punctual",
    "Responsible",
    "Accountable",
    "Ethical",
    "Integrity",
    "Honest",
  ],
  "Adaptability & Flexibility": [
    "Adaptability",
    "Flexibility",
    "Versatility",
    "Agility",
    "Resilience",
    "Open-Minded",
    "Willingness to Learn",
    "Growth Mindset",
    "Continuous Learning",
    "Curiosity",
  ],
  "Organization & Time Management": [
    "Organization",
    "Organizational",
    "Time Management",
    "Planning",
    "Prioritization",
    "Multi-tasking",
    "Detail-Oriented",
    "Thorough",
    "Meticulous",
    "Efficient",
    "Productivity",
  ],
  "Leadership & Management": [
    "Leadership",
    "Management",
    "Supervision",
    "Delegation",
    "Motivation",
    "Inspiration",
    "Influence",
    "Direction",
    "Guidance",
    "Visionary",
    "Strategic",
    "Executive",
  ],
  "Creativity & Innovation": [
    "Creativity",
    "Creative",
    "Innovation",
    "Innovative",
    "Originality",
    "Original",
    "Imagination",
    "Inventive",
    "Design Thinking",
    "Brainstorming",
    "Ideation",
  ],
  "Customer & Service Orientation": [
    "Customer-Focused",
    "Customer Service",
    "Client Relations",
    "User-Centered",
    "Patient",
    "Empathetic",
    "Responsive",
    "Attentive",
    "Supportive",
  ],
  "Project & Task Management": [
    "Project Management",
    "Task Management",
    "Coordination",
    "Execution",
    "Implementation",
    "Follow-through",
    "Delivery",
    "Results-Oriented",
    "Goal-Oriented",
    "Achievement",
  ],
  "Stress Management": [
    "Stress Management",
    "Pressure Handling",
    "Calm",
    "Composed",
    "Poised",
    "Level-Headed",
    "Balanced",
    "Mindful",
    "Self-Aware",
    "Self-Control",
  ],
}

// Flatten the soft skills map for easier lookup
export const softSkills = Object.values(softSkillsMap).flat()

// Requirements organized by category
export const requirementsMap: Record<string, string[]> = {
  Education: [
    "Bachelor's",
    "Master's",
    "MBA",
    "PhD",
    "Doctorate",
    "Degree",
    "Diploma",
    "Certificate",
    "Certification",
    "Licensed",
    "Accredited",
    "Graduate",
    "Undergraduate",
  ],
  Experience: [
    "1+ years",
    "2+ years",
    "3+ years",
    "4+ years",
    "5+ years",
    "7+ years",
    "10+ years",
    "Years of experience",
    "Experienced",
    "Seasoned",
    "Veteran",
    "Junior",
    "Mid-level",
    "Senior",
    "Lead",
    "Principal",
    "Expert",
    "Specialist",
    "Professional",
  ],
  "Work Arrangements": [
    "Remote",
    "Hybrid",
    "On-site",
    "In-office",
    "Telecommute",
    "Work from Home",
    "Flexible",
    "Relocation",
    "Travel",
    "International",
    "Domestic",
    "Local",
  ],
  "Employment Type": [
    "Full-time",
    "Part-time",
    "Contract",
    "Contractor",
    "Freelance",
    "Permanent",
    "Temporary",
    "Seasonal",
    "Internship",
    "Co-op",
    "Apprenticeship",
  ],
  "Career Level": [
    "Entry-level",
    "Junior",
    "Mid-level",
    "Senior",
    "Lead",
    "Manager",
    "Director",
    "Executive",
    "C-level",
    "VP",
    "Head of",
    "Chief",
  ],
  "Clearance & Background": [
    "Security Clearance",
    "Background Check",
    "Drug Test",
    "Criminal Record Check",
    "Reference Check",
    "Credit Check",
    "Screening",
  ],
  "Specific Requirements": [
    "Required",
    "Mandatory",
    "Essential",
    "Must-have",
    "Preferred",
    "Desired",
    "Nice-to-have",
    "Bonus",
    "Plus",
    "Advantage",
  ],
  Qualifications: [
    "Qualified",
    "Proficient",
    "Skilled",
    "Competent",
    "Capable",
    "Knowledgeable",
    "Familiar",
    "Understanding",
    "Expertise",
    "Mastery",
    "Fluent",
    "Native",
  ],
  "Specific Phrases": [
    "Ability to",
    "Capable of",
    "Responsible for",
    "Accountable for",
    "Experience with",
    "Experience in",
    "Knowledge of",
    "Understanding of",
    "Familiarity with",
    "Proficiency in",
    "Expertise in",
    "Industry experience",
    "Strong understanding",
    "Good understanding",
  ],
}

// Flatten the requirements map for easier lookup
export const requirements = Object.values(requirementsMap).flat()

export const normalizeSkillName = (skill: string): string => {
  return skill
    .trim()
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .replace(/\s+/g, " ")
    .toLowerCase()
}

export const stopwords = [
  "ability",
  "able",
  "about",
  "above",
  "abroad",
  "according",
  "accordingly",
  "across",
  "actually",
  "adj",
  "after",
  "afterwards",
  "again",
  "against",
  "ago",
  "ahead",
  "ain't",
  "all",
  "allow",
  "allows",
  "almost",
  "alone",
  "along",
  "alongside",
  "already",
  "also",
  "although",
  "always",
  "am",
  "amid",
  "amidst",
  "among",
  "amongst",
  "an",
  "and",
  "another",
  "any",
  "anybody",
  "anyhow",
  "anyone",
  "anything",
  "anyway",
  "anyways",
  "anywhere",
  "apart",
  "appear",
  "appreciate",
  "appropriate",
  "are",
  "aren't",
  "around",
  "as",
  "a's",
  "aside",
  "ask",
  "asking",
  "associated",
  "at",
  "available",
  "away",
  "awfully",
  "be",
  "became",
  "because",
  "become",
  "becomes",
  "becoming",
  "been",
  "before",
  "beforehand",
  "begin",
  "behind",
  "being",
  "believe",
  "below",
  "beside",
  "besides",
  "best",
  "better",
  "between",
  "beyond",
  "both",
  "brief",
  "but",
  "by",
  "came",
  "can",
  "cannot",
  "cant",
  "can't",
  "caption",
  "cause",
  "causes",
  "certain",
  "certainly",
  "changes",
  "clearly",
  "c'mon",
  "co",
  "co.",
  "com",
  "come",
  "comes",
  "coming",
  "commonly",
  "compare",
  "completely",
  "concerning",
  "consequently",
  "consider",
  "considering",
  "contain",
  "containing",
  "contains",
  "corresponding",
  "could",
  "couldn't",
  "course",
  "currently",
  "definitely",
  "described",
  "despite",
  "did",
  "didn't",
  "different",
  "directly",
  "do",
  "does",
  "doesn't",
  "doing",
  "done",
  "don't",
  "down",
  "downwards",
  "during",
  "each",
  "edu",
  "eg",
  "eight",
  "either",
  "else",
  "elsewhere",
  "enough",
  "entirely",
  "especially",
  "et",
  "etc",
  "even",
  "ever",
  "every",
  "everybody",
  "everyone",
  "everything",
  "everywhere",
  "ex",
  "exactly",
  "example",
  "except",
  "fairly",
  "far",
  "few",
  "fewer",
  "fifth",
  "first",
  "five",
  "followed",
  "following",
  "follows",
  "for",
  "forever",
  "former",
  "formerly",
  "forth",
  "forward",
  "found",
  "four",
  "from",
  "further",
  "furthermore",
  "get",
  "gets",
  "getting",
  "given",
  "gives",
  "go",
  "goes",
  "going",
  "gone",
  "got",
  "gotten",
  "greetings",
  "had",
  "hadn't",
  "half",
  "happens",
  "hardly",
  "has",
  "hasn't",
  "have",
  "haven't",
  "having",
  "he",
  "he'd",
  "he'll",
  "hello",
  "help",
  "hence",
  "her",
  "here",
  "hereafter",
  "hereby",
  "herein",
  "here's",
  "hereupon",
  "hers",
  "herself",
  "he's",
  "hi",
  "him",
  "himself",
  "his",
  "hither",
  "hopefully",
  "how",
  "howbeit",
  "however",
  "how's",
  "i",
  "i'd",
  "ie",
  "if",
  "ignored",
  "i'll",
  "i'm",
  "immediate",
  "in",
  "inasmuch",
  "inc",
  "indeed",
  "indicate",
  "indicated",
  "indicates",
  "inner",
  "inside",
  "insofar",
  "instead",
  "into",
  "inward",
  "is",
  "isn't",
  "it",
  "it'd",
  "it'll",
  "its",
  "it's",
  "itself",
  "i've",
  "just",
  "keep",
  "keeps",
  "kept",
  "know",
  "known",
  "knows",
  "last",
  "lately",
  "later",
  "latter",
  "latterly",
  "least",
  "less",
  "lest",
  "let",
  "let's",
  "like",
  "liked",
  "likely",
  "likewise",
  "little",
  "look",
  "looking",
  "looks",
  "ltd",
  "mainly",
  "many",
  "may",
  "maybe",
  "me",
  "mean",
  "meanwhile",
  "merely",
  "might",
  "more",
  "moreover",
  "most",
  "mostly",
  "much",
  "must",
  "my",
  "myself",
  "name",
  "namely",
  "nd",
  "near",
  "nearly",
  "necessary",
  "need",
  "needs",
  "neither",
  "never",
  "nevertheless",
  "new",
  "next",
  "nine",
  "no",
  "nobody",
  "non",
  "none",
  "nonetheless",
  "noone",
  "nor",
  "normally",
  "not",
  "nothing",
  "novel",
  "now",
  "nowhere",
  "obviously",
  "of",
  "off",
  "often",
  "oh",
  "ok",
  "okay",
  "old",
  "on",
  "once",
  "one",
  "ones",
  "one's",
  "only",
  "onto",
  "opposite",
  "or",
  "other",
  "others",
  "otherwise",
  "ought",
  "our",
  "ours",
  "ourselves",
  "out",
  "outside",
  "over",
  "overall",
  "own",
  "particular",
  "particularly",
  "perhaps",
  "placed",
  "please",
  "plus",
  "possible",
  "presumably",
  "probably",
  "provided",
  "provides",
  "que",
  "quite",
  "qv",
  "rather",
  "rd",
  "re",
  "really",
  "reasonably",
  "regarding",
  "regardless",
  "regards",
  "relatively",
  "respectively",
  "right",
  "round",
  "said",
  "same",
  "saw",
  "say",
  "saying",
  "says",
  "second",
  "secondly",
  "see",
  "seeing",
  "seem",
  "seemed",
  "seeming",
  "seems",
  "seen",
  "self",
  "selves",
  "sensible",
  "sent",
  "serious",
  "seriously",
  "seven",
  "several",
  "shall",
  "she",
  "she'd",
  "she'll",
  "she's",
  "should",
  "shouldn't",
  "since",
  "six",
  "so",
  "some",
  "somebody",
  "someday",
  "somehow",
  "someone",
  "something",
  "sometime",
  "sometimes",
  "somewhat",
  "somewhere",
  "soon",
  "sorry",
  "specified",
  "specify",
  "specifying",
  "still",
  "sub",
  "such",
  "sup",
  "sure",
  "take",
  "taken",
  "taking",
  "tell",
  "tends",
  "th",
  "than",
  "thank",
  "thanks",
  "thanx",
  "that",
  "that'll",
  "thats",
  "that's",
  "that've",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "thence",
  "there",
  "thereafter",
  "thereby",
  "there'd",
  "therefore",
  "therein",
  "there'll",
  "there's",
  "theres",
  "thereupon",
  "there've",
  "these",
  "they",
  "they'd",
  "they'll",
  "they're",
  "they've",
  "thing",
  "things",
  "think",
  "third",
  "thirty",
  "this",
  "thorough",
  "thoroughly",
  "those",
  "though",
  "three",
  "through",
  "throughout",
  "thru",
  "thus",
  "till",
  "to",
  "together",
  "too",
  "took",
  "toward",
  "towards",
  "tried",
  "tries",
  "truly",
  "try",
  "trying",
  "t's",
  "twice",
  "two",
  "un",
  "under",
  "underneath",
  "undoing",
  "unfortunately",
  "unless",
  "unlike",
  "unlikely",
  "until",
  "unto",
  "up",
  "upon",
  "upwards",
  "us",
  "use",
  "used",
  "useful",
  "uses",
  "using",
  "usually",
  "v",
  "value",
  "various",
  "very",
  "via",
  "viz",
  "vs",
  "want",
  "wants",
  "was",
  "wasn't",
  "way",
  "we",
  "we'd",
  "welcome",
  "well",
  "we'll",
  "went",
  "were",
  "weren't",
  "we've",
  "what",
  "whatever",
  "what'll",
  "what's",
  "what've",
  "when",
  "whence",
  "whenever",
  "when's",
  "where",
  "whereafter",
  "whereas",
  "whereby",
  "wherein",
  "where's",
  "whereupon",
  "wherever",
  "whether",
  "which",
  "whichever",
  "while",
  "whilst",
  "whither",
  "who",
  "who'd",
  "whoever",
  "whole",
  "who'll",
  "whom",
  "whomever",
  "who's",
  "whose",
  "why",
  "why's",
  "will",
  "willing",
  "wish",
  "with",
  "within",
  "without",
  "wonder",
  "won't",
  "would",
  "wouldn't",
  "yes",
  "yet",
  "you",
  "you'd",
  "you'll",
  "your",
  "you're",
  "yours",
  "yourself",
  "yourselves",
  "you've",
  "zero",
]

export const isValidSkill = (term: string): boolean => {
  const normalized = term.toLowerCase().trim()

  if (stopwords.includes(normalized)) {
    return false
  }

  if (normalized.length < 2) {
    return false
  }

  if (/^\d+$/.test(normalized)) {
    return false
  }

  return true
}
