/**
 * Curated lists of skills and requirements for job analysis
 */

// Technical skills organized by category
export const technicalSkillsMap: Record<string, string[]> = {
  "Programming Languages": [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "PHP",
    "Ruby",
    "Go",
    "Golang",
    "Swift",
    "Kotlin",
    "Rust",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Shell",
    "Bash",
    "PowerShell",
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "PHP",
    "Ruby",
    "Go",
    "Golang",
    "Swift",
    "Kotlin",
    "Rust",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Shell",
    "Bash",
    "PowerShell",
  ],
  "Web Technologies": [
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "SASS",
    "SCSS",
    "Less",
    "Bootstrap",
    "Tailwind",
    "Material UI",
    "React",
    "Angular",
    "Vue",
    "Svelte",
    "jQuery",
    "Redux",
    "Next.js",
    "Gatsby",
    "Nuxt",
    "Express",
    "Node.js",
    "Deno",
    "Electron",
    "PWA",
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "SASS",
    "SCSS",
    "Less",
    "Bootstrap",
    "Tailwind",
    "Material UI",
    "React",
    "Angular",
    "Vue",
    "Svelte",
    "jQuery",
    "Redux",
    "Next.js",
    "Gatsby",
    "Nuxt",
    "Express",
    "Node.js",
    "Deno",
    "Electron",
    "PWA",
  ],
  "Frameworks & Libraries": [
    "Laravel",
    "Django",
    "Flask",
    "Spring",
    "ASP.NET",
    "Rails",
    "Symfony",
    "CodeIgniter",
    "Struts",
    "Hibernate",
    "Entity Framework",
    "NestJS",
    "FastAPI",
    "Pandas",
    "NumPy",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "Laravel",
    "Django",
    "Flask",
    "Spring",
    "ASP.NET",
    "Rails",
    "Symfony",
    "CodeIgniter",
    "Struts",
    "Hibernate",
    "Entity Framework",
    "NestJS",
    "FastAPI",
    "Pandas",
    "NumPy",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
  ],
  Databases: [
    "SQL",
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "SQLite",
    "MongoDB",
    "Cassandra",
    "Redis",
    "DynamoDB",
    "Elasticsearch",
    "Neo4j",
    "MariaDB",
    "Firebase",
    "Firestore",
    "Supabase",
    "CouchDB",
    "GraphQL",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "SQLite",
    "MongoDB",
    "Cassandra",
    "Redis",
    "DynamoDB",
    "Elasticsearch",
    "Neo4j",
    "MariaDB",
    "Firebase",
    "Firestore",
    "Supabase",
    "CouchDB",
    "GraphQL",
  ],
  "Cloud & DevOps": [
    "AWS",
    "Azure",
    "GCP",
    "Google Cloud",
    "Heroku",
    "Netlify",
    "Vercel",
    "Docker",
    "Kubernetes",
    "K8s",
    "CI/CD",
    "Jenkins",
    "Travis",
    "CircleCI",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "Puppet",
    "Chef",
    "Prometheus",
    "Grafana",
    "DevOps",
    "AWS",
    "Azure",
    "GCP",
    "Google Cloud",
    "Heroku",
    "Netlify",
    "Vercel",
    "Docker",
    "Kubernetes",
    "K8s",
    "CI/CD",
    "Jenkins",
    "Travis",
    "CircleCI",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "Puppet",
    "Chef",
    "Prometheus",
    "Grafana",
    "DevOps",
  ],
  "Tools & Version Control": [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Mercurial",
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Monday",
    "Notion",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Photoshop",
    "Illustrator",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Mercurial",
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Monday",
    "Notion",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Photoshop",
    "Illustrator",
  ],
  "Microsoft Technologies": [
    ".NET",
    ".NET Core",
    "ASP.NET",
    "WPF",
    "WCF",
    "LINQ",
    "SharePoint",
    "Dynamics 365",
    "Power BI",
    "Power Apps",
    "Power Automate",
    "Office 365",
    "Azure DevOps",
    ".NET",
    ".NET Core",
    "ASP.NET",
    "WPF",
    "WCF",
    "LINQ",
    "SharePoint",
    "Dynamics 365",
    "Power BI",
    "Power Apps",
    "Power Automate",
    "Office 365",
    "Azure DevOps",
  ],
  Mobile: [
    "Android",
    "iOS",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Cordova",
    "SwiftUI",
    "UIKit",
    "Kotlin",
    "Objective-C",
    "Dart",
    "Android",
    "iOS",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Cordova",
    "SwiftUI",
    "UIKit",
    "Kotlin",
    "Objective-C",
    "Dart",
  ],
  Testing: [
    "Jest",
    "Mocha",
    "Chai",
    "Jasmine",
    "Cypress",
    "Selenium",
    "Puppeteer",
    "JUnit",
    "NUnit",
    "xUnit",
    "TestNG",
    "PHPUnit",
    "RSpec",
    "Pytest",
    "TDD",
    "BDD",
    "Unit Testing",
    "Integration Testing",
    "E2E Testing",
    "Jest",
    "Mocha",
    "Chai",
    "Jasmine",
    "Cypress",
    "Selenium",
    "Puppeteer",
    "JUnit",
    "NUnit",
    "xUnit",
    "TestNG",
    "PHPUnit",
    "RSpec",
    "Pytest",
    "TDD",
    "BDD",
    "Unit Testing",
    "Integration Testing",
    "E2E Testing",
  ],
  "Architecture & Patterns": [
    "REST",
    "SOAP",
    "API",
    "Microservices",
    "Serverless",
    "MVC",
    "MVVM",
    "OOP",
    "Functional Programming",
    "Design Patterns",
    "SOLID",
    "DRY",
    "KISS",
    "DDD",
    "REST",
    "SOAP",
    "API",
    "Microservices",
    "Serverless",
    "MVC",
    "MVVM",
    "OOP",
    "Functional Programming",
    "Design Patterns",
    "SOLID",
    "DRY",
    "KISS",
    "DDD",
  ],
  Security: [
    "OAuth",
    "JWT",
    "SAML",
    "SSO",
    "HTTPS",
    "SSL",
    "TLS",
    "Encryption",
    "Authentication",
    "Authorization",
    "OWASP",
    "Penetration Testing",
    "Security Audit",
    "Vulnerability Assessment",
    "OAuth",
    "JWT",
    "SAML",
    "SSO",
    "HTTPS",
    "SSL",
    "TLS",
    "Encryption",
    "Authentication",
    "Authorization",
    "OWASP",
    "Penetration Testing",
    "Security Audit",
    "Vulnerability Assessment",
  ],
  "Data Science & AI": [
    "Machine Learning",
    "Deep Learning",
    "AI",
    "Artificial Intelligence",
    "NLP",
    "Natural Language Processing",
    "Computer Vision",
    "Data Mining",
    "Big Data",
    "Data Warehouse",
    "ETL",
    "Data Lake",
    "Hadoop",
    "Spark",
    "Kafka",
    "Machine Learning",
    "Deep Learning",
    "AI",
    "Artificial Intelligence",
    "NLP",
    "Natural Language Processing",
    "Computer Vision",
    "Data Mining",
    "Big Data",
    "Data Warehouse",
    "ETL",
    "Data Lake",
    "Hadoop",
    "Spark",
    "Kafka",
  ],
  "Web Servers & Protocols": [
    "Apache",
    "Nginx",
    "IIS",
    "HTTP",
    "HTTPS",
    "WebSockets",
    "TCP/IP",
    "DNS",
    "FTP",
    "SMTP",
    "IMAP",
    "POP3",
    "Apache",
    "Nginx",
    "IIS",
    "HTTP",
    "HTTPS",
    "WebSockets",
    "TCP/IP",
    "DNS",
    "FTP",
    "SMTP",
    "IMAP",
    "POP3",
  ],
}

// Flatten the technical skills map for easier lookup
export const technicalSkills = Object.values(technicalSkillsMap).flat()

// Soft skills organized by category
export const softSkillsMap: Record<string, string[]> = {
  "Communication & Interpersonal": [
    "Communication",
    "Interpersonal",
    "Presentation",
    "Public Speaking",
    "Writing",
    "Listening",
    "Negotiation",
    "Persuasion",
    "Conflict Resolution",
    "Diplomacy",
    "Empathy",
    "Emotional Intelligence",
    "Communication",
    "Interpersonal",
    "Presentation",
    "Public Speaking",
    "Writing",
    "Listening",
    "Negotiation",
    "Persuasion",
    "Conflict Resolution",
    "Diplomacy",
    "Empathy",
    "Emotional Intelligence",
  ],
  "Teamwork & Collaboration": [
    "Teamwork",
    "Collaboration",
    "Team Player",
    "Cooperative",
    "Cross-functional",
    "Relationship Building",
    "Networking",
    "Partnership",
    "Mentoring",
    "Coaching",
    "Training",
    "Teamwork",
    "Collaboration",
    "Team Player",
    "Cooperative",
    "Cross-functional",
    "Relationship Building",
    "Networking",
    "Partnership",
    "Mentoring",
    "Coaching",
    "Training",
  ],
  "Problem Solving & Critical Thinking": [
    "Problem-Solving",
    "Critical Thinking",
    "Analytical",
    "Analysis",
    "Troubleshooting",
    "Debugging",
    "Decision-Making",
    "Judgment",
    "Reasoning",
    "Logic",
    "Strategic Thinking",
    "Systems Thinking",
    "Problem-Solving",
    "Critical Thinking",
    "Analytical",
    "Analysis",
    "Troubleshooting",
    "Debugging",
    "Decision-Making",
    "Judgment",
    "Reasoning",
    "Logic",
    "Strategic Thinking",
    "Systems Thinking",
  ],
  "Work Ethic & Attitude": [
    "Self-Motivated",
    "Initiative",
    "Proactive",
    "Driven",
    "Ambitious",
    "Dedicated",
    "Committed",
    "Reliable",
    "Dependable",
    "Punctual",
    "Responsible",
    "Accountable",
    "Ethical",
    "Integrity",
    "Honest",
    "Self-Motivated",
    "Initiative",
    "Proactive",
    "Driven",
    "Ambitious",
    "Dedicated",
    "Committed",
    "Reliable",
    "Dependable",
    "Punctual",
    "Responsible",
    "Accountable",
    "Ethical",
    "Integrity",
    "Honest",
  ],
  "Adaptability & Flexibility": [
    "Adaptability",
    "Flexibility",
    "Versatility",
    "Agility",
    "Resilience",
    "Open-Minded",
    "Willingness to Learn",
    "Growth Mindset",
    "Continuous Learning",
    "Curiosity",
    "Adaptability",
    "Flexibility",
    "Versatility",
    "Agility",
    "Resilience",
    "Open-Minded",
    "Willingness to Learn",
    "Growth Mindset",
    "Continuous Learning",
    "Curiosity",
  ],
  "Organization & Time Management": [
    "Organization",
    "Organizational",
    "Time Management",
    "Planning",
    "Prioritization",
    "Multi-tasking",
    "Detail-Oriented",
    "Thorough",
    "Meticulous",
    "Efficient",
    "Productivity",
    "Organization",
    "Organizational",
    "Time Management",
    "Planning",
    "Prioritization",
    "Multi-tasking",
    "Detail-Oriented",
    "Thorough",
    "Meticulous",
    "Efficient",
    "Productivity",
  ],
  "Leadership & Management": [
    "Leadership",
    "Management",
    "Supervision",
    "Delegation",
    "Motivation",
    "Inspiration",
    "Influence",
    "Direction",
    "Guidance",
    "Visionary",
    "Strategic",
    "Executive",
    "Leadership",
    "Management",
    "Supervision",
    "Delegation",
    "Motivation",
    "Inspiration",
    "Influence",
    "Direction",
    "Guidance",
    "Visionary",
    "Strategic",
    "Executive",
  ],
  "Creativity & Innovation": [
    "Creativity",
    "Creative",
    "Innovation",
    "Innovative",
    "Originality",
    "Original",
    "Imagination",
    "Inventive",
    "Design Thinking",
    "Brainstorming",
    "Ideation",
    "Creativity",
    "Creative",
    "Innovation",
    "Innovative",
    "Originality",
    "Original",
    "Imagination",
    "Inventive",
    "Design Thinking",
    "Brainstorming",
    "Ideation",
  ],
  "Customer & Service Orientation": [
    "Customer-Focused",
    "Customer Service",
    "Client Relations",
    "User-Centered",
    "Patient",
    "Empathetic",
    "Responsive",
    "Attentive",
    "Supportive",
    "Customer-Focused",
    "Customer Service",
    "Client Relations",
    "User-Centered",
    "Patient",
    "Empathetic",
    "Responsive",
    "Attentive",
    "Supportive",
  ],
  "Project & Task Management": [
    "Project Management",
    "Task Management",
    "Coordination",
    "Execution",
    "Implementation",
    "Follow-through",
    "Delivery",
    "Results-Oriented",
    "Goal-Oriented",
    "Achievement",
    "Project Management",
    "Task Management",
    "Coordination",
    "Execution",
    "Implementation",
    "Follow-through",
    "Delivery",
    "Results-Oriented",
    "Goal-Oriented",
    "Achievement",
  ],
  "Stress Management": [
    "Stress Management",
    "Pressure Handling",
    "Calm",
    "Composed",
    "Poised",
    "Level-Headed",
    "Balanced",
    "Mindful",
    "Self-Aware",
    "Self-Control",
    "Stress Management",
    "Pressure Handling",
    "Calm",
    "Composed",
    "Poised",
    "Level-Headed",
    "Balanced",
    "Mindful",
    "Self-Aware",
    "Self-Control",
  ],
}

// Flatten the soft skills map for easier lookup
export const softSkills = Object.values(softSkillsMap).flat()

// Requirements organized by category
export const requirementsMap: Record<string, string[]> = {
  Education: [
    "Bachelor's",
    "Master's",
    "MBA",
    "PhD",
    "Doctorate",
    "Degree",
    "Diploma",
    "Certificate",
    "Certification",
    "Licensed",
    "Accredited",
    "Graduate",
    "Undergraduate",
    "Bachelor's",
    "Master's",
    "MBA",
    "PhD",
    "Doctorate",
    "Degree",
    "Diploma",
    "Certificate",
    "Certification",
    "Licensed",
    "Accredited",
    "Graduate",
    "Undergraduate",
  ],
  Experience: [
    "1+ years",
    "2+ years",
    "3+ years",
    "4+ years",
    "5+ years",
    "7+ years",
    "10+ years",
    "Years of experience",
    "Experienced",
    "Seasoned",
    "Veteran",
    "Junior",
    "Mid-level",
    "Senior",
    "Lead",
    "Principal",
    "Expert",
    "Specialist",
    "Professional",
    "1+ years",
    "2+ years",
    "3+ years",
    "4+ years",
    "5+ years",
    "7+ years",
    "10+ years",
    "Years of experience",
    "Experienced",
    "Seasoned",
    "Veteran",
    "Junior",
    "Mid-level",
    "Senior",
    "Lead",
    "Principal",
    "Expert",
    "Specialist",
    "Professional",
  ],
  "Work Arrangements": [
    "Remote",
    "Hybrid",
    "On-site",
    "In-office",
    "Telecommute",
    "Work from Home",
    "Flexible",
    "Relocation",
    "Travel",
    "International",
    "Domestic",
    "Local",
    "Remote",
    "Hybrid",
    "On-site",
    "In-office",
    "Telecommute",
    "Work from Home",
    "Flexible",
    "Relocation",
    "Travel",
    "International",
    "Domestic",
    "Local",
  ],
  "Employment Type": [
    "Full-time",
    "Part-time",
    "Contract",
    "Contractor",
    "Freelance",
    "Permanent",
    "Temporary",
    "Seasonal",
    "Internship",
    "Co-op",
    "Apprenticeship",
    "Full-time",
    "Part-time",
    "Contract",
    "Contractor",
    "Freelance",
    "Permanent",
    "Temporary",
    "Seasonal",
    "Internship",
    "Co-op",
    "Apprenticeship",
  ],
  "Career Level": [
    "Entry-level",
    "Junior",
    "Mid-level",
    "Senior",
    "Lead",
    "Manager",
    "Director",
    "Executive",
    "C-level",
    "VP",
    "Head of",
    "Chief",
    "Entry-level",
    "Junior",
    "Mid-level",
    "Senior",
    "Lead",
    "Manager",
    "Director",
    "Executive",
    "C-level",
    "VP",
    "Head of",
    "Chief",
  ],
  "Clearance & Background": [
    "Security Clearance",
    "Background Check",
    "Drug Test",
    "Criminal Record Check",
    "Reference Check",
    "Credit Check",
    "Screening",
    "Security Clearance",
    "Background Check",
    "Drug Test",
    "Criminal Record Check",
    "Reference Check",
    "Credit Check",
    "Screening",
  ],
  "Specific Requirements": [
    "Required",
    "Mandatory",
    "Essential",
    "Must-have",
    "Preferred",
    "Desired",
    "Nice-to-have",
    "Bonus",
    "Plus",
    "Advantage",
    "Required",
    "Mandatory",
    "Essential",
    "Must-have",
    "Preferred",
    "Desired",
    "Nice-to-have",
    "Bonus",
    "Plus",
    "Advantage",
  ],
  Qualifications: [
    "Qualified",
    "Proficient",
    "Skilled",
    "Competent",
    "Capable",
    "Knowledgeable",
    "Familiar",
    "Understanding",
    "Expertise",
    "Mastery",
    "Fluent",
    "Native",
    "Qualified",
    "Proficient",
    "Skilled",
    "Competent",
    "Capable",
    "Knowledgeable",
    "Familiar",
    "Understanding",
    "Expertise",
    "Mastery",
    "Fluent",
    "Native",
  ],
  "Specific Phrases": [
    "Ability to",
    "Capable of",
    "Responsible for",
    "Accountable for",
    "Experience with",
    "Experience in",
    "Knowledge of",
    "Understanding of",
    "Familiarity with",
    "Proficiency in",
    "Expertise in",
    "Industry experience",
    "Strong understanding",
    "Good understanding",
    "Ability to",
    "Capable of",
    "Responsible for",
    "Accountable for",
    "Experience with",
    "Experience in",
    "Knowledge of",
    "Understanding of",
    "Familiarity with",
    "Proficiency in",
    "Expertise in",
    "Industry experience",
    "Strong understanding",
    "Good understanding",
  ],
}

// Flatten the requirements map for easier lookup
export const requirements = Object.values(requirementsMap).flat()

// Stopwords and common phrases that should not be considered as skills
export const stopwords = [
  "a",
  "an",
  "the",
  "and",
  "or",
  "but",
  "if",
  "then",
  "else",
  "when",
  "up",
  "down",
  "in",
  "out",
  "on",
  "off",
  "over",
  "under",
  "again",
  "further",
  "then",
  "once",
  "here",
  "there",
  "when",
  "where",
  "why",
  "how",
  "all",
  "any",
  "both",
  "each",
  "few",
  "more",
  "most",
  "other",
  "some",
  "such",
  "no",
  "nor",
  "not",
  "only",
  "own",
  "same",
  "so",
  "than",
  "too",
  "very",
  "s",
  "t",
  "can",
  "will",
  "just",
  "don",
  "should",
  "now",
  "d",
  "ll",
  "m",
  "o",
  "re",
  "ve",
  "y",
  "ain",
  "aren",
  "couldn",
  "didn",
  "doesn",
  "hadn",
  "hasn",
  "haven",
  "isn",
  "ma",
  "mightn",
  "mustn",
  "needn",
  "shan",
  "shouldn",
  "wasn",
  "weren",
  "won",
  "wouldn",
  "lis",
  "oops",
  "soa",
  "moq",
  "soap",
  "css",
  "api",
  "web",
  "app",
  "solid",
  "rest",
  "ws",
  "wsdl",
  "t-sql",
  "pl-sql",
  "pi-sql",
  "web api",
  "web service",
  "i",
  "basic",
  "profile",
  "of",
  "to",
  "with",
  "in",
  "for",
  "have",
  "has",
  "had",
  "skills",
  "skill",
  "experience",
  "experiences",
  "understanding",
  "good",
  "strong",
  "preferred",
  "must",
  "daily",
  "client",
  "independently",
  "manage",
  "tight",
  "schedules",
  "work",
  "working",
  "stakeholder",
  "expectations",
  "decision",
  "making",
  "adaptable",
  "flexible",
  "ability",
  "prioritize",
  "communication",
  "services",
  "principle",
  "dependency",
  "injection",
  "agile",
  "financial",
  "asset",
  "management",
  "functions",
  "service",
  "profile",
  "problem",
  "solving",
  "experienced",
  "skilled",
  "industry",
]

// Function to normalize a skill name
export function normalizeSkillName(name: string): string {
  return name
    .trim()
    .replace(/[-_/]/g, " ") // Replace hyphens, underscores, and slashes with spaces
    .replace(/\s+/g, " ") // Replace multiple spaces with a single space
    .replace(/\b\w/g, (c) => c.toUpperCase()) // Capitalize first letter of each word
}

// Function to check if a term is a valid skill
export function isValidSkill(term: string): boolean {
  const normalized = term.toLowerCase().trim()

  // Check if it's in the stopwords list
  if (stopwords.includes(normalized)) {
    return false
  }

  // Check if it's too short (less than 2 characters)
  if (normalized.length < 2) {
    return false
  }

  // Check if it's just a number
  if (/^\d+$/.test(normalized)) {
    return false
  }

  return true
}

// Function to categorize a skill
export function categorizeSkill(skill: string): "technical" | "soft" | "requirement" | "unknown" {
  const normalized = skill.toLowerCase().trim()

  // Check technical skills
  if (technicalSkills.some((s) => s.toLowerCase() === normalized)) {
    return "technical"
  }

  // Check soft skills
  if (softSkills.some((s) => s.toLowerCase() === normalized)) {
    return "soft"
  }

  // Check requirements
  if (requirements.some((s) => s.toLowerCase() === normalized)) {
    return "requirement"
  }

  return "unknown"
}

// Function to get similar skills (for suggestions)
export function getSimilarSkills(input: string, limit = 5): string[] {
  const normalized = input.toLowerCase().trim()

  // If input is empty, return empty array
  if (!normalized) {
    return []
  }

  // Combine all skills
  const allSkills = [...technicalSkills, ...softSkills, ...requirements]

  // Filter skills that include the input (case-insensitive)
  const matches = allSkills.filter((skill) => skill.toLowerCase().includes(normalized))

  // Get unique matches
  const uniqueMatches = Array.from(new Set(matches));

  // Return the top unique matches
  return uniqueMatches.slice(0, limit)
} 